import {
  type LuaAstNode,
  getStringLiteralText,
  isIdentifierNamed,
  parseRisuLuaSource,
  walkLuaAst,
} from './risulua-forbidden-analyzer';
import type { RisuLuaModuleGraph, RisuLuaResolvedModule } from './risulua-modular-resolver';

/**
 * RisuLua 모듈 그래프 번들링 옵션 정의.
 */
export interface BundleRisuLuaModularGraphOptions {
  /** 번들링할 모듈 그래프. */
  graph: RisuLuaModuleGraph;
}

/**
 * 번들링된 RisuLua 출력 결과 정의.
 */
export interface RisuLuaBundledOutput {
  /** 생성된 Lua 코드 문자열. */
  code: string;
  /** 생성된 로더 함수 이름 목록. */
  generatedLoaders: string[];
  /** 교체된 require 호출 정보 목록. */
  replacedRequires: Array<{
    moduleId: string;
    requireId: string;
    loaderName: string;
  }>;
}

/**
 * 해결된 RisuLua 모듈 그래프를 단일 Lua 문자열로 번들링함.
 *
 * - 의존성 모듈은 생성된 로컬 로더 함수와 캐시 테이블로 래핑됨
 * - 진입점 모듈(메인)은 래핑 없이 최상위에 출력됨
 * - 정적 require("id") 호출은 로더 함수 호출로 교체됨
 * - 모듈이 nil을 반환하면 Lua require 동작을 모방하기 위해 true를 캐시함
 * - 호스트 전역변수(getChatVar, setChatVar, json, async 등)는 그대로 유지됨
 */
export function bundleRisuLuaModularGraph(
  options: BundleRisuLuaModularGraphOptions,
): RisuLuaBundledOutput {
  const { graph } = options;

  // 모듈 ID → 모듈 매핑을 빠르게 조회할 수 있도록 구성함
  const moduleMap = new Map<string, RisuLuaResolvedModule>();
  for (const module of graph.modules) {
    moduleMap.set(module.id, module);
  }

  // 의존성 모듈(진입점이 아닌 모듈) 추적
  const dependencyIds = graph.modules
    .filter((m) => m.id !== graph.entryId)
    .map((m) => m.id);

  // 각 의존성에 대해 결정적인 로더 이름 생성
  const loaderNames = new Map<string, string>();
  for (const id of dependencyIds) {
    loaderNames.set(id, generateLoaderName(id));
  }

  // require 교체 맵 구성: 각 require 엣지에 대해 (fromModule, requireId) → loaderName 매핑
  const requireReplacements = new Map<string, string>();
  for (const edge of graph.edges) {
    const key = `${edge.from}:${edge.requireId}`;
    const loaderName = loaderNames.get(edge.to);
    if (loaderName) {
      requireReplacements.set(key, loaderName);
    }
  }

  // 결과 수집
  const generatedLoaders: string[] = [];
  const replacedRequires: Array<{
    moduleId: string;
    requireId: string;
    loaderName: string;
  }> = [];

  // 출력 부분 구성
  const outputParts: string[] = [];

  // 1. 캐시 테이블 출력
  outputParts.push('-- Generated by RisuLua modular bundler');
  outputParts.push('local __risulua_cache = {}');
  outputParts.push('');

  // 2. 모든 로컬 로더 선언(Lua 렉시컬 스코핑 안전을 위해)
  // 그 다음 로더 함수 본문 출력. 이를 통해 모든 로더가 서로의 스코프에 존재함.
  const sortedDependencyIds = [...dependencyIds].sort();

  // 의존성이 있을 때만 로더 선언과 본문 출력
  if (sortedDependencyIds.length > 0) {
    // 2a. 전방 선언: local __loader_a, __loader_b, ...
    const loaderLocalDeclarations = sortedDependencyIds
      .map((id) => loaderNames.get(id)!)
      .join(', ');
    outputParts.push(`local ${loaderLocalDeclarations}`);
    outputParts.push('');

    // 2b. 함수 본문 할당
    for (const moduleId of sortedDependencyIds) {
    const module = moduleMap.get(moduleId)!;
    const loaderName = loaderNames.get(moduleId)!;

    // 로더 함수 본문 할당 생성
    const loaderCode = generateLoaderFunctionBody({
      loaderName,
      moduleId,
      source: module.source,
      requireReplacements,
    });

    outputParts.push(loaderCode);
    outputParts.push('');
    generatedLoaders.push(loaderName);

      // 이 모듈의 교체된 require 추적
      for (const edge of module.requires) {
        const replacementLoader = loaderNames.get(edge.to);
        if (replacementLoader) {
          replacedRequires.push({
            moduleId,
            requireId: edge.requireId,
            loaderName: replacementLoader,
          });
        }
      }
    }
  }

  // 3. 진입점 모듈(메인)을 require 교체와 함께 최상위에 출력
  const entryModule = moduleMap.get(graph.entryId)!;
  const entryCode = replaceRequiresInSource({
    source: entryModule.source,
    moduleId: graph.entryId,
    requireReplacements,
  });

  // 진입점 모듈의 교체된 require 추적
  for (const edge of entryModule.requires) {
    const replacementLoader = loaderNames.get(edge.to);
    if (replacementLoader) {
      replacedRequires.push({
        moduleId: graph.entryId,
        requireId: edge.requireId,
        loaderName: replacementLoader,
      });
    }
  }

  outputParts.push(entryCode);

  return {
    code: outputParts.join('\n'),
    generatedLoaders,
    replacedRequires,
  };
}

/**
 * 로더 함수 생성 옵션 정의.
 */
interface GenerateLoaderOptions {
  /** 로더 함수 이름. */
  loaderName: string;
  /** 모듈 ID. */
  moduleId: string;
  /** 모듈 소스 코드. */
  source: string;
  /** require 교체 매핑. */
  requireReplacements: Map<string, string>;
}

/**
 * 로더 함수 본문 생성.
 * @param options - 로더 생성 옵션
 * @returns 생성된 로더 함수 코드 문자열
 */
function generateLoaderFunctionBody(options: GenerateLoaderOptions): string {
  const { loaderName, moduleId, source, requireReplacements } = options;

    // 모듈 소스의 require 호출 교체
    const transformedSource = replaceRequiresInSource({
      source,
      moduleId,
      requireReplacements,
    });

  // 로더 함수 본문 할당 생성(로컬 선언이 아님)
  // 로컬은 렉시컬 스코핑 안전을 위해 앞서 선언됨
  const parts: string[] = [];
  parts.push(`${loaderName} = function()`);
  parts.push(`  if __risulua_cache["${moduleId}"] ~= nil then`);
  parts.push(`    return __risulua_cache["${moduleId}"]`);
  parts.push(`  end`);
  parts.push(`  local __risulua_module_result = (function()`);
  // 변환된 소스 들여쓰기
  const indentedSource = transformedSource
    .split('\n')
    .map((line) => '    ' + line)
    .join('\n');
  parts.push(indentedSource);
  parts.push(`  end)()`);
  parts.push(`  if __risulua_module_result == nil then`);
  parts.push(`    __risulua_cache["${moduleId}"] = true`);
  parts.push(`  else`);
  parts.push(`    __risulua_cache["${moduleId}"] = __risulua_module_result`);
  parts.push(`  end`);
  parts.push(`  return __risulua_cache["${moduleId}"]`);
  parts.push(`end`);

  return parts.join('\n');
}

/**
 * require 교체 옵션 정의.
 */
interface ReplaceRequiresOptions {
  /** 소스 코드 문자열. */
  source: string;
  /** 모듈 ID. */
  moduleId: string;
  /** require 교체 매핑. */
  requireReplacements: Map<string, string>;
}

/**
 * 소스 코드에서 require 호출 교체.
 * @param options - require 교체 옵션
 * @returns 교체된 소스 코드 문자열
 */
function replaceRequiresInSource(options: ReplaceRequiresOptions): string {
  const { source, moduleId, requireReplacements } = options;

  // 실행 가능한 require 호출을 찾기 위해 소스 파싱
  let ast: LuaAstNode;
  try {
    ast = parseRisuLuaSource(source);
  } catch (error) {
    // 파싱 실패는 의도적인 폴백: 리졸버가 이미 소스를 검증함.
    // 번들링이 계속되도록 소스를 변경 없이 반환함.
    void error; // 에러가 의도적으로 사용되지 않음을 명시적으로 표시함
    return source;
  }

  // 교체가 필요한 모든 require 호출 표현식 수집
  const replacements: Array<{
    start: number;
    end: number;
    replacement: string;
  }> = [];

  walkLuaAst(ast, (node) => {
    if (node.type !== 'CallExpression' || !isIdentifierNamed(node.base, 'require')) {
      return;
    }

    const args = Array.isArray(node.arguments) ? node.arguments : [];
    const requireId = args.length === 1 ? getStringLiteralText(args[0]) : null;
    if (!requireId) {
      return; // 정적 require가 아니면 건너뛰기(리졸버가 이미 거부했을 것임)
    }

    const key = `${moduleId}:${requireId}`;
    const loaderName = requireReplacements.get(key);

    if (loaderName) {
      // 교체를 위한 범위 가져오기
      const range = (node as unknown as { range?: [number, number] }).range;
      if (range && Array.isArray(range) && range.length === 2) {
        replacements.push({
          start: range[0],
          end: range[1],
          replacement: `${loaderName}()`,
        });
      }
    }
  });

  // 오프셋 드리프트를 피하기 위해 끝에서 시작 순으로 정렬
  replacements.sort((a, b) => b.start - a.start);

  // 교체 적용
  let result = source;
  for (const { start, end, replacement } of replacements) {
    result = result.slice(0, start) + replacement + result.slice(end);
  }

  return result;
}

/**
 * 모듈 ID에서 안전한 로더 함수 이름 생성.
 * 점을 밑줄로 변환하고 __loader_ 접두사를 붙임.
 * @param moduleId - 모듈 ID
 * @returns 생성된 로더 함수 이름
 */
function generateLoaderName(moduleId: string): string {
  // 점을 밑줄로 교체하고 정제
  const sanitized = moduleId.replace(/[^A-Za-z0-9_.]/g, '_').replace(/\./g, '_');
  return `__loader_${sanitized}`;
}

/**
 * 번들링된 출력에 실행 가능한 require 호출 노드가 있는지 확인.
 * 모든 require가 교체되었는지 검증하는 데 사용됨.
 * @param code - 검사할 Lua 코드
 * @returns require 호출이 있으면 true, 없으면 false
 */
export function hasExecutableRequireCalls(code: string): boolean {
  try {
    const ast = parseRisuLuaSource(code);
    let hasRequire = false;

    walkLuaAst(ast, (node) => {
      if (node.type === 'CallExpression' && isIdentifierNamed(node.base, 'require')) {
        hasRequire = true;
      }
    });

    return hasRequire;
  } catch (error) {
    // 검증에서 파싱 실패는 보수적으로 처리: require 호출이 있다고 가정함.
    void error; // 에러가 의도적으로 사용되지 않음을 명시적으로 표시함
    return true;
  }
}

/**
 * 번들링된 출력에서 모든 전역 함수 선언 추출.
 * 훅 보존 검증에 사용됨.
 * @param code - 검사할 Lua 코드
 * @returns 전역 함수 이름 목록
 */
export function extractGlobalFunctionDeclarations(code: string): string[] {
  try {
    const ast = parseRisuLuaSource(code);
    const globals: string[] = [];

    walkLuaAst(ast, (node) => {
      // 전역 함수 선언 찾기: function name() ... end
      if (node.type === 'FunctionDeclaration' && node.identifier?.name) {
        // 전역인지 확인(로컬이 아님)
        if (!node.isLocal) {
          globals.push(node.identifier.name);
        }
      }
    });

    return globals;
  } catch (error) {
    // 검증에서 파싱 실패는 빈 전역 목록을 반환함.
    void error; // 에러가 의도적으로 사용되지 않음을 명시적으로 표시함
    return [];
  }
}
