import {
  type LuaAstNode,
  getStringLiteralText,
  isIdentifierNamed,
  parseRisuLuaSource,
  walkLuaAst,
} from './risulua-forbidden-analyzer';
import type { RisuLuaModuleGraph, RisuLuaResolvedModule } from './risulua-modular-resolver';

/**
 * RisuLua 모듈 그래프 번들링 옵션 정의.
 */
export interface BundleRisuLuaModularGraphOptions {
  /** 번들링할 모듈 그래프. */
  graph: RisuLuaModuleGraph;
}

/**
 * 번들링된 RisuLua 출력 결과 정의.
 */
export interface RisuLuaBundledOutput {
  /** 생성된 Lua 코드 문자열. */
  code: string;
  /** 생성된 로더 함수 이름 목록. */
  generatedLoaders: string[];
  /** 교체된 require 호출 정보 목록. */
  replacedRequires: Array<{
    moduleId: string;
    requireId: string;
    loaderName: string;
  }>;
}

interface LuaCommentNode {
  range?: [number, number];
}

interface LuaAstWithComments extends LuaAstNode {
  comments?: LuaCommentNode[];
}

const RISULUA_LOADER_REGISTRY_NAME = '__risulua_loaders';

/**
 * 해결된 RisuLua 모듈 그래프를 단일 Lua 문자열로 번들링함.
 *
 * - 의존성 모듈은 생성된 로컬 로더 함수와 캐시 테이블로 래핑됨
 * - 진입점 모듈(메인)은 래핑 없이 최상위에 출력됨
 * - 정적 require("id") 호출은 로더 함수 호출로 교체됨
 * - 모듈이 nil을 반환하면 Lua require 동작을 모방하기 위해 true를 캐시함
 * - 호스트 전역변수(getChatVar, setChatVar, json, async 등)는 그대로 유지됨
 */
export function bundleRisuLuaModularGraph(
  options: BundleRisuLuaModularGraphOptions,
): RisuLuaBundledOutput {
  const { graph } = options;

  // 모듈 ID → 모듈 매핑을 빠르게 조회할 수 있도록 구성함
  const moduleMap = new Map<string, RisuLuaResolvedModule>();
  for (const module of graph.modules) {
    moduleMap.set(module.id, module);
  }

  // 의존성 모듈(진입점이 아닌 모듈) 추적
  const dependencyIds = graph.modules
    .filter((m) => m.id !== graph.entryId)
    .map((m) => m.id);

  // 각 의존성에 대해 결정적인 로더 이름 생성
  const loaderNames = new Map<string, string>();
  for (const id of dependencyIds) {
    loaderNames.set(id, generateLoaderName(id));
  }

  // require 교체 맵 구성: 각 require 엣지에 대해 (fromModule, requireId) → moduleId 매핑
  const requireReplacements = new Map<string, string>();
  for (const edge of graph.edges) {
    const key = `${edge.from}:${edge.requireId}`;
    if (loaderNames.has(edge.to)) {
      requireReplacements.set(key, edge.to);
    }
  }

  // 결과 수집
  const generatedLoaders: string[] = [];
  const replacedRequires: Array<{
    moduleId: string;
    requireId: string;
    loaderName: string;
  }> = [];

  // 출력 부분 구성
  const outputParts: string[] = [];

  // 1. 캐시 테이블 출력
  outputParts.push('-- Generated by RisuLua modular bundler');
  outputParts.push('local __risulua_cache = {}');
  outputParts.push('');

  // 2. 의존성 로더 registry와 로더 함수 본문 출력.
  // 테이블 lookup은 많은 의존성에서도 top-level local budget을 고정 크기로 유지함.
  const sortedDependencyIds = [...dependencyIds].sort();

  // 의존성이 있을 때만 로더 registry와 본문 출력
  if (sortedDependencyIds.length > 0) {
    outputParts.push(`local ${RISULUA_LOADER_REGISTRY_NAME} = {}`);
    outputParts.push('');

    for (const moduleId of sortedDependencyIds) {
      const module = moduleMap.get(moduleId)!;
      const loaderName = loaderNames.get(moduleId)!;

      // 로더 함수 본문 할당 생성
      const loaderCode = generateLoaderFunctionBody({
        loaderName,
        moduleId,
        source: module.source,
        requireReplacements,
      });

      outputParts.push(loaderCode);
      outputParts.push('');
      generatedLoaders.push(loaderName);

      // 이 모듈의 교체된 require 추적
      for (const edge of module.requires) {
        const replacementLoader = loaderNames.get(edge.to);
        if (replacementLoader) {
          replacedRequires.push({
            moduleId,
            requireId: edge.requireId,
            loaderName: replacementLoader,
          });
        }
      }
    }
  }

  // 3. 진입점 모듈(메인)을 require 교체와 함께 최상위에 출력
  const entryModule = moduleMap.get(graph.entryId)!;
  const entryCode = replaceRequiresInSource({
    source: entryModule.source,
    moduleId: graph.entryId,
    requireReplacements,
  });

  // 진입점 모듈의 교체된 require 추적
  for (const edge of entryModule.requires) {
    const replacementLoader = loaderNames.get(edge.to);
    if (replacementLoader) {
      replacedRequires.push({
        moduleId: graph.entryId,
        requireId: edge.requireId,
        loaderName: replacementLoader,
      });
    }
  }

  outputParts.push(entryCode);

  return {
    code: stripLuaComments(outputParts.join('\n')),
    generatedLoaders,
    replacedRequires,
  };
}

function stripLuaComments(code: string): string {
  let ast: LuaAstWithComments;
  try {
    ast = parseRisuLuaSource(code) as LuaAstWithComments;
  } catch (error) {
    void error;
    return code;
  }

  const comments = ast.comments ?? [];
  if (comments.length === 0) return code;

  let output = code;
  for (const comment of [...comments].sort((left, right) => (right.range?.[0] ?? 0) - (left.range?.[0] ?? 0))) {
    const range = comment.range;
    if (range === undefined) continue;
    output = output.slice(0, range[0]) + preserveNewlinesAsWhitespace(output.slice(range[0], range[1])) + output.slice(range[1]);
  }
  return output;
}

function preserveNewlinesAsWhitespace(text: string): string {
  return text.replace(/[^\r\n]/g, ' ');
}

/**
 * 로더 함수 생성 옵션 정의.
 */
interface GenerateLoaderOptions {
  /** 로더 함수 이름. */
  loaderName: string;
  /** 모듈 ID. */
  moduleId: string;
  /** 모듈 소스 코드. */
  source: string;
  /** require 교체 매핑. */
  requireReplacements: Map<string, string>;
}

/**
 * 로더 함수 본문 생성.
 * @param options - 로더 생성 옵션
 * @returns 생성된 로더 함수 코드 문자열
 */
function generateLoaderFunctionBody(options: GenerateLoaderOptions): string {
  const { moduleId, source, requireReplacements } = options;

  // 안전한 export alias를 먼저 낮춘 뒤 모듈 소스의 require 호출을 교체함.
  const aliasRewrittenSource = rewriteSafeModuleExportAliases(source);
  const requireRewrittenSource = replaceRequiresInSource({
    source: aliasRewrittenSource,
    moduleId,
    requireReplacements,
  });
  const transformedSource = rewriteSingleUseGeneratedDependencyAliases(requireRewrittenSource);

  const moduleKey = JSON.stringify(moduleId);
  const parts: string[] = [];
  parts.push(`${RISULUA_LOADER_REGISTRY_NAME}[${moduleKey}] = function()`);
  parts.push(`  if __risulua_cache[${moduleKey}] ~= nil then`);
  parts.push(`    return __risulua_cache[${moduleKey}]`);
  parts.push(`  end`);
  parts.push(`  local __risulua_module_result = (function()`);
  // 변환된 소스 들여쓰기
  const indentedSource = transformedSource
    .split('\n')
    .map((line) => '    ' + line)
    .join('\n');
  parts.push(indentedSource);
  parts.push(`  end)()`);
  parts.push(`  if __risulua_module_result == nil then`);
  parts.push(`    __risulua_cache[${moduleKey}] = true`);
  parts.push(`  else`);
  parts.push(`    __risulua_cache[${moduleKey}] = __risulua_module_result`);
  parts.push(`  end`);
  parts.push(`  return __risulua_cache[${moduleKey}]`);
  parts.push(`end`);

  return parts.join('\n');
}

function rewriteSafeModuleExportAliases(source: string): string {
  let ast: LuaAstNode;
  try {
    ast = parseRisuLuaSource(source);
  } catch (error) {
    void error;
    return source;
  }

  const body = Array.isArray(ast.body) ? ast.body : [];
  const replacements: Array<{ start: number; end: number; replacement: string }> = [];

  for (let index = 0; index < body.length - 1; index += 1) {
    const declaration = body[index];
    const assignment = body[index + 1];
    const rewrite = getSafeExportAliasRewrite(source, declaration, assignment, body, index);
    if (rewrite) replacements.push(rewrite);
  }

  replacements.sort((left, right) => right.start - left.start);
  let rewritten = source;
  for (const replacement of replacements) {
    rewritten = rewritten.slice(0, replacement.start) + replacement.replacement + rewritten.slice(replacement.end);
  }
  return rewritten;
}

function getSafeExportAliasRewrite(
  source: string,
  declaration: LuaAstNode,
  assignment: LuaAstNode,
  body: LuaAstNode[],
  declarationIndex: number,
): { start: number; end: number; replacement: string } | null {
  const functionRewrite = getSafeLocalFunctionExportRewrite(source, declaration, assignment, body, declarationIndex);
  if (functionRewrite) return functionRewrite;

  if (declaration.type !== 'LocalStatement') return null;
  const variables = Array.isArray(declaration.variables) ? declaration.variables : [];
  const init = Array.isArray(declaration.init) ? declaration.init : [];
  if (variables.length !== 1 || init.length !== 1) return null;

  const variable = variables[0];
  if (!isIdentifierNode(variable)) return null;

  if (assignment.type !== 'AssignmentStatement') return null;
  const assignmentVariables = Array.isArray(assignment.variables) ? assignment.variables : [];
  const assignmentInit = Array.isArray(assignment.init) ? assignment.init : [];
  if (assignmentVariables.length !== 1 || assignmentInit.length !== 1) return null;

  const target = assignmentVariables[0];
  const value = assignmentInit[0];
  if (!isModuleExportMember(target, variable.name)) return null;
  if (!isIdentifierNamed(value, variable.name)) return null;
  if (containsIdentifierName(init[0], variable.name)) return null;
  if (statementsContainIdentifierName(body.slice(declarationIndex + 2), variable.name)) return null;

  const declarationRange = getNodeRange(declaration);
  const initRange = getNodeRange(init[0]);
  const assignmentTargetRange = getNodeRange(target);
  const assignmentRange = getNodeRange(assignment);
  if (!declarationRange || !initRange || !assignmentTargetRange || !assignmentRange) return null;

  const assignmentTarget = source.slice(assignmentTargetRange[0], assignmentTargetRange[1]);
  const initializer = source.slice(initRange[0], initRange[1]);
  return {
    start: declarationRange[0],
    end: assignmentRange[1],
    replacement: `${assignmentTarget} = ${initializer}`,
  };
}

function getSafeLocalFunctionExportRewrite(
  source: string,
  declaration: LuaAstNode,
  assignment: LuaAstNode,
  body: LuaAstNode[],
  declarationIndex: number,
): { start: number; end: number; replacement: string } | null {
  if (declaration.type !== 'FunctionDeclaration' || declaration.isLocal !== true) return null;
  const functionName = declaration.identifier;
  if (!isIdentifierNode(functionName)) return null;

  if (assignment.type !== 'AssignmentStatement') return null;
  const assignmentVariables = Array.isArray(assignment.variables) ? assignment.variables : [];
  const assignmentInit = Array.isArray(assignment.init) ? assignment.init : [];
  if (assignmentVariables.length !== 1 || assignmentInit.length !== 1) return null;

  const target = assignmentVariables[0];
  const value = assignmentInit[0];
  if (!isModuleExportMember(target, functionName.name)) return null;
  if (!isIdentifierNamed(value, functionName.name)) return null;
  if (statementsContainIdentifierName(body.slice(0, declarationIndex), functionName.name)) return null;
  if (statementsContainIdentifierName(asNodeArray(declaration.body), functionName.name)) return null;
  if (statementsContainIdentifierName(body.slice(declarationIndex + 2), functionName.name)) return null;

  const declarationRange = getNodeRange(declaration);
  const assignmentTargetRange = getNodeRange(target);
  const assignmentRange = getNodeRange(assignment);
  if (!declarationRange || !assignmentTargetRange || !assignmentRange) return null;

  const declarationText = source.slice(declarationRange[0], declarationRange[1]);
  const assignmentTarget = source.slice(assignmentTargetRange[0], assignmentTargetRange[1]);
  const functionPrefix = new RegExp(`^local\\s+function\\s+${escapeRegExp(functionName.name)}\\b`);
  if (!functionPrefix.test(declarationText)) return null;

  return {
    start: declarationRange[0],
    end: assignmentRange[1],
    replacement: declarationText.replace(functionPrefix, `function ${assignmentTarget}`),
  };
}

function rewriteSingleUseGeneratedDependencyAliases(source: string): string {
  let ast: LuaAstNode;
  try {
    ast = parseRisuLuaSource(source);
  } catch (error) {
    void error;
    return source;
  }

  const body = Array.isArray(ast.body) ? ast.body : [];
  const replacements: Array<{ start: number; end: number; replacement: string }> = [];

  for (let index = 0; index < body.length; index += 1) {
    const declaration = body[index];
    const rewrite = getSingleUseGeneratedDependencyAliasRewrite(source, declaration, body, index);
    if (rewrite) replacements.push(...rewrite);
  }

  replacements.sort((left, right) => right.start - left.start);
  let rewritten = source;
  for (const replacement of replacements) {
    rewritten = rewritten.slice(0, replacement.start) + replacement.replacement + rewritten.slice(replacement.end);
  }
  return rewritten;
}

function getSingleUseGeneratedDependencyAliasRewrite(
  source: string,
  declaration: LuaAstNode,
  body: LuaAstNode[],
  declarationIndex: number,
): Array<{ start: number; end: number; replacement: string }> | null {
  if (declaration.type !== 'LocalStatement') return null;
  const variables = Array.isArray(declaration.variables) ? declaration.variables : [];
  const init = Array.isArray(declaration.init) ? declaration.init : [];
  if (variables.length !== 1 || init.length !== 1) return null;

  const variable = variables[0];
  if (!isIdentifierNode(variable) || !variable.name.startsWith('__')) return null;
  const declarationRange = getNodeRange(declaration);
  const initRange = getNodeRange(init[0]);
  if (!declarationRange || !initRange) return null;

  const initializer = source.slice(initRange[0], initRange[1]);
  if (!isGeneratedLoaderCall(initializer)) return null;

  const references = collectTopLevelIdentifierReferences(body, variable.name, declarationIndex + 1);
  if (references.length !== 1) return null;

  const [reference] = references;
  if (!isInlineableAliasReference(reference)) return null;
  if (!hasOnlySafeInterveningAliasStatements(body, declarationIndex + 1, reference.statementIndex)) return null;

  return [
    { start: reference.range[0], end: reference.range[1], replacement: initializer },
    { start: declarationRange[0], end: includeTrailingLineBreak(source, declarationRange[1]), replacement: '' },
  ];
}

interface IdentifierReference {
  node: LuaAstNode;
  parent: LuaAstNode | null;
  statement: LuaAstNode;
  statementIndex: number;
  range: [number, number];
}

function collectTopLevelIdentifierReferences(body: LuaAstNode[], name: string, startIndex: number): IdentifierReference[] {
  const references: IdentifierReference[] = [];
  for (let index = startIndex; index < body.length; index += 1) {
    const statement = body[index];
    walkLuaAst(statement, (node, parent) => {
      if (!isIdentifierNamed(node, name)) return;
      const range = getNodeRange(node);
      if (!range) return;
      references.push({ node, parent, statement, statementIndex: index, range });
    });
  }
  return references;
}

function isInlineableAliasReference(reference: IdentifierReference): boolean {
  const { parent, statement, node } = reference;
  if (!parent) return false;
  if (parent.type === 'AssignmentStatement') {
    const variables = Array.isArray(parent.variables) ? parent.variables : [];
    const init = Array.isArray(parent.init) ? parent.init : [];
    return statement === parent && init.includes(node) && !variables.includes(node);
  }
  if (parent.type === 'LocalStatement') {
    const variables = Array.isArray(parent.variables) ? parent.variables : [];
    const init = Array.isArray(parent.init) ? parent.init : [];
    return statement === parent && init.includes(node) && !variables.includes(node);
  }
  if (statement.type === 'ReturnStatement') {
    const args = Array.isArray(statement.arguments) ? statement.arguments : [];
    return parent === statement && args.includes(node);
  }
  return false;
}

function hasOnlySafeInterveningAliasStatements(body: LuaAstNode[], startIndex: number, endIndex: number): boolean {
  for (let index = startIndex; index < endIndex; index += 1) {
    if (!isLocalEmptyModuleTableDeclaration(body[index])) return false;
  }
  return true;
}

function isLocalEmptyModuleTableDeclaration(statement: LuaAstNode): boolean {
  if (statement.type !== 'LocalStatement') return false;
  const variables = Array.isArray(statement.variables) ? statement.variables : [];
  const init = Array.isArray(statement.init) ? statement.init : [];
  return variables.length === 1 && init.length === 1 && isIdentifierNamed(variables[0], 'M') && isEmptyTableConstructor(init[0]);
}

function isEmptyTableConstructor(node: LuaAstNode | undefined): boolean {
  if (node?.type !== 'TableConstructorExpression') return false;
  const fields = getNodeArrayProperty(node, 'fields');
  const elements = getNodeArrayProperty(node, 'elements');
  return fields.length === 0 && elements.length === 0;
}

function getNodeArrayProperty(node: LuaAstNode, key: string): LuaAstNode[] {
  const value = node[key];
  return Array.isArray(value) ? value.filter(isNode) : [];
}

function isGeneratedLoaderCall(source: string): boolean {
  return /^__risulua_loaders\[[\s\S]+\]\(\)$/.test(source.trim());
}

function includeTrailingLineBreak(source: string, end: number): number {
  if (source[end] === '\r' && source[end + 1] === '\n') return end + 2;
  if (source[end] === '\n' || source[end] === '\r') return end + 1;
  return end;
}

function isIdentifierNode(node: unknown): node is LuaAstNode & { name: string } {
  return isNode(node) && node.type === 'Identifier' && typeof node.name === 'string';
}

function isModuleExportMember(node: unknown, memberName: string): boolean {
  if (!isNode(node) || node.type !== 'MemberExpression') return false;
  const member = node as LuaAstNode & { base?: LuaAstNode; identifier?: LuaAstNode; indexer?: string };
  return isIdentifierNamed(member.base, 'M') && member.indexer === '.' && isIdentifierNamed(member.identifier, memberName);
}

function containsIdentifierName(node: LuaAstNode, name: string): boolean {
  let found = false;
  walkLuaAst(node, (child) => {
    if (isIdentifierNamed(child, name)) found = true;
  });
  return found;
}

function statementsContainIdentifierName(statements: LuaAstNode[], name: string): boolean {
  return statements.some((statement) => containsIdentifierName(statement, name));
}

function asNodeArray(value: unknown): LuaAstNode[] {
  return Array.isArray(value) ? value.filter(isNode) : [];
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function getNodeRange(node: unknown): [number, number] | null {
  const range = (node as { range?: unknown })?.range;
  return Array.isArray(range) && range.length === 2 && typeof range[0] === 'number' && typeof range[1] === 'number'
    ? [range[0], range[1]]
    : null;
}

function isNode(value: unknown): value is LuaAstNode {
  return Boolean(value) && typeof value === 'object' && typeof (value as { type?: unknown }).type === 'string';
}

/**
 * require 교체 옵션 정의.
 */
interface ReplaceRequiresOptions {
  /** 소스 코드 문자열. */
  source: string;
  /** 모듈 ID. */
  moduleId: string;
  /** require 교체 매핑. */
  requireReplacements: Map<string, string>;
}

/**
 * 소스 코드에서 require 호출 교체.
 * @param options - require 교체 옵션
 * @returns 교체된 소스 코드 문자열
 */
function replaceRequiresInSource(options: ReplaceRequiresOptions): string {
  const { source, moduleId, requireReplacements } = options;

  // 실행 가능한 require 호출을 찾기 위해 소스 파싱
  let ast: LuaAstNode;
  try {
    ast = parseRisuLuaSource(source);
  } catch (error) {
    // 파싱 실패는 의도적인 폴백: 리졸버가 이미 소스를 검증함.
    // 번들링이 계속되도록 소스를 변경 없이 반환함.
    void error; // 에러가 의도적으로 사용되지 않음을 명시적으로 표시함
    return source;
  }

  // 교체가 필요한 모든 require 호출 표현식 수집
  const replacements: Array<{
    start: number;
    end: number;
    replacement: string;
  }> = [];

  walkLuaAst(ast, (node) => {
    if (node.type !== 'CallExpression' || !isIdentifierNamed(node.base, 'require')) {
      return;
    }

    const args = Array.isArray(node.arguments) ? node.arguments : [];
    const requireId = args.length === 1 ? getStringLiteralText(args[0]) : null;
    if (!requireId) {
      return; // 정적 require가 아니면 건너뛰기(리졸버가 이미 거부했을 것임)
    }

    const key = `${moduleId}:${requireId}`;
    const replacementModuleId = requireReplacements.get(key);

    if (replacementModuleId) {
      // 교체를 위한 범위 가져오기
      const range = (node as unknown as { range?: [number, number] }).range;
      if (range && Array.isArray(range) && range.length === 2) {
        replacements.push({
          start: range[0],
          end: range[1],
          replacement: `${RISULUA_LOADER_REGISTRY_NAME}[${JSON.stringify(replacementModuleId)}]()`,
        });
      }
    }
  });

  // 오프셋 드리프트를 피하기 위해 끝에서 시작 순으로 정렬
  replacements.sort((a, b) => b.start - a.start);

  // 교체 적용
  let result = source;
  for (const { start, end, replacement } of replacements) {
    result = result.slice(0, start) + replacement + result.slice(end);
  }

  return result;
}

/**
 * 모듈 ID에서 안전한 로더 함수 이름 생성.
 * 점을 밑줄로 변환하고 __loader_ 접두사를 붙임.
 * @param moduleId - 모듈 ID
 * @returns 생성된 로더 함수 이름
 */
function generateLoaderName(moduleId: string): string {
  // 점을 밑줄로 교체하고 정제
  const sanitized = moduleId.replace(/[^A-Za-z0-9_.]/g, '_').replace(/\./g, '_');
  return `__loader_${sanitized}`;
}

/**
 * 번들링된 출력에 실행 가능한 require 호출 노드가 있는지 확인.
 * 모든 require가 교체되었는지 검증하는 데 사용됨.
 * @param code - 검사할 Lua 코드
 * @returns require 호출이 있으면 true, 없으면 false
 */
export function hasExecutableRequireCalls(code: string): boolean {
  try {
    const ast = parseRisuLuaSource(code);
    let hasRequire = false;

    walkLuaAst(ast, (node) => {
      if (node.type === 'CallExpression' && isIdentifierNamed(node.base, 'require')) {
        hasRequire = true;
      }
    });

    return hasRequire;
  } catch (error) {
    // 검증에서 파싱 실패는 보수적으로 처리: require 호출이 있다고 가정함.
    void error; // 에러가 의도적으로 사용되지 않음을 명시적으로 표시함
    return true;
  }
}

/**
 * 번들링된 출력에서 모든 전역 함수 선언 추출.
 * 훅 보존 검증에 사용됨.
 * @param code - 검사할 Lua 코드
 * @returns 전역 함수 이름 목록
 */
export function extractGlobalFunctionDeclarations(code: string): string[] {
  try {
    const ast = parseRisuLuaSource(code);
    const globals: string[] = [];

    walkLuaAst(ast, (node) => {
      // 전역 함수 선언 찾기: function name() ... end
      if (node.type === 'FunctionDeclaration' && node.identifier?.name) {
        // 전역인지 확인(로컬이 아님)
        if (!node.isLocal) {
          globals.push(node.identifier.name);
        }
      }
    });

    return globals;
  } catch (error) {
    // 검증에서 파싱 실패는 빈 전역 목록을 반환함.
    void error; // 에러가 의도적으로 사용되지 않음을 명시적으로 표시함
    return [];
  }
}
