import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {
  RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
  RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
  RISULUA_MODULE_TABLE_DOMAIN_CANDIDATES_PATH,
  RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
  RISULUA_MODULE_TABLE_REFACTOR_MAP_PATH,
  createEmptyRisuLuaModuleTableHostEffects,
  createRisuLuaModuleTableDomainCandidatesDocument,
  createRisuLuaModuleTableRefactorMapDocument,
  renderRisuLuaSplitReport,
  serializeRisuLuaModuleTableDomainCandidates,
  serializeRisuLuaModuleTableRefactorMap,
  writeRisuLuaModuleTableDomainCandidates,
  writeRisuLuaModuleTableRefactorMap,
  type RisuLuaModuleTableRefactorMapContract,
  type RisuLuaSplitPlan,
} from '../src/domain/risulua-split';
import type { LuaSourceRange } from '../src/domain/risulua-split';

describe('risulua-split module-table schema and report rendering', () => {
  it('renders module-table report sections without changing base report sections', () => {
    const refactorMap = createSyntheticRefactorMap();
    const report = renderRisuLuaSplitReport({
      plan: createSyntheticModuleTablePlan(),
      moduleTableRefactorMap: refactorMap,
      profileMap: ['Module-table synthetic fixture records report-only schema contracts.'],
      pureCandidates: ['trim -> lua/common/local_helpers.risulua'],
      runtimeCoupledHelpers: ['normalizeOutput -> lua/handler_helpers/output_helpers.risulua'],
      riskyBlocks: ['rerollChoices stays in main due to preserve:host-visible-global-unsafe-bridge'],
      dynamicPatterns: ['_G[dynamicName] preserved as preserve:dynamic-global-reference-risk'],
      refactorTasks: ['Review deck candidate before creating a domain module.'],
      verificationSuggestions: ['Validate docs/refactor-map.json and docs/domain-candidates.json.'],
    });

    expect(report).toContain('## Summary');
    expect(report).toContain('## Module-table extraction contract');
    expect(report).toContain(`- Refactor map: \`${RISULUA_MODULE_TABLE_REFACTOR_MAP_PATH}\``);
    expect(report).toContain(`- Domain candidates: \`${RISULUA_MODULE_TABLE_DOMAIN_CANDIDATES_PATH}\``);
    expect(report).toContain('### Runtime roots and modules');
    expect(report).toContain('`onOutput` (top-level-global-function, bridge:host-visible-global, lines 20-28)');
    expect(report).toContain('`lua/common/local_helpers.risulua` (common-helper, alias `__local_helpers`, exports `trim`)');
    expect(report).toContain('`lua/handler_helpers/output_helpers.risulua` (handler-helper, alias `__output_helpers`, exports `normalizeOutput`)');
    expect(report).toContain('`lua/host_globals/global_functions.risulua` (host-global, alias `__host_globals`, exports `onOutput`)');
    expect(report).toContain('`lua/host_globals/async_actions.risulua` (host-global, alias `__async_actions`, exports `runModel`)');
    expect(report).toContain('`onOutput` stays host-visible through direct assignment `onOutput = __host_globals.onOutput`');
    expect(report).toContain('`rerollChoices` preserved because `preserve:host-visible-global-unsafe-bridge`');
    expect(report).toContain('`proceduralInit` remains procedural report-only code because `preserve:top-level-side-effect`');
    expect(report).toContain('- reads: `getChatVar`, `getState`');
    expect(report).toContain('- writes: `setState`');
    expect(report).toContain('- uiInteraction: `alertNormal`, `reloadDisplay`');
    expect(report).toContain('- asyncModelNetwork: `LLM`, `request`');
    expect(report).toContain('- dynamicEnvironment: `_G`, `load`');
    expect(report).toContain('`deck` confidence 0.82; proposed target `lua/domain/deck.risulua`; generationStatus=report-only; autoGenerated=false');
    expect(report).toContain('`extract:pure-helper`');
    expect(report).toContain('`preserve:async-boundary-risk`');
    expect(report).toContain('## Validator results');
  });

  it('serializes first-class refactor-map and domain-candidates JSON documents', () => {
    const refactorMap = createSyntheticRefactorMap();
    const refactorJson = serializeRisuLuaModuleTableRefactorMap(refactorMap, { cwd: process.cwd() });
    const domainJson = serializeRisuLuaModuleTableDomainCandidates(refactorMap.domainCandidates, { cwd: process.cwd() });
    const refactorDocument = JSON.parse(refactorJson) as ReturnType<typeof createRisuLuaModuleTableRefactorMapDocument>;
    const domainDocument = JSON.parse(domainJson) as ReturnType<typeof createRisuLuaModuleTableDomainCandidatesDocument>;

    expect(refactorDocument).toEqual(expect.objectContaining({
      version: 1,
      mode: 'module-table',
      sourceFile: '<repo-root>/fixtures/source.risulua',
      source: { file: '<repo-root>/fixtures/source.risulua' },
    }));
    expect(refactorDocument.modules.map((moduleContract) => moduleContract.path)).toEqual([
      RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
      'lua/handler_helpers/output_helpers.risulua',
      RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
      RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
    ]);
    expect(refactorDocument.artifacts).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, exports: ['trim'] }),
      expect.objectContaining({ path: RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH, exports: ['runModel'] }),
    ]));
    expect(refactorDocument.bridges).toEqual([expect.objectContaining({
      originalPublicName: 'onOutput',
      assignment: 'onOutput = __host_globals.onOutput',
    })]);
    expect(refactorDocument.hostEffects).toEqual({
      reads: ['getChatVar', 'getState'],
      writes: ['setState'],
      uiInteraction: ['alertNormal', 'reloadDisplay'],
      asyncModelNetwork: ['LLM', 'request'],
      dynamicEnvironment: ['_G', 'load'],
    });
    expect(refactorDocument.warnings).toEqual([]);
    expect(refactorDocument.domainCandidates.every((candidate) => candidate.autoGenerated === false)).toBe(true);
    expect(domainDocument).toEqual({
      version: 1,
      mode: 'module-table',
      candidates: refactorDocument.domainCandidates,
    });
    expect(domainDocument.candidates[0]).toEqual(expect.objectContaining({
      name: 'deck',
      confidence: 0.82,
      recommendedPath: 'lua/domain/deck.risulua',
      autoGenerated: false,
    }));
  });

  it('writes only docs JSON artifacts for module-table schema rendering', () => {
    withTempDir((outputRoot) => {
      const refactorMap = createSyntheticRefactorMap();
      const refactorWrite = writeRisuLuaModuleTableRefactorMap(refactorMap, { outputRoot, cwd: process.cwd() });
      const domainWrite = writeRisuLuaModuleTableDomainCandidates(refactorMap.domainCandidates, { outputRoot, cwd: process.cwd() });

      expect(refactorWrite.path).toBe(path.join(outputRoot, ...RISULUA_MODULE_TABLE_REFACTOR_MAP_PATH.split('/')));
      expect(domainWrite.path).toBe(path.join(outputRoot, ...RISULUA_MODULE_TABLE_DOMAIN_CANDIDATES_PATH.split('/')));
      expect(fs.existsSync(refactorWrite.path)).toBe(true);
      expect(fs.existsSync(domainWrite.path)).toBe(true);
      expect(fs.existsSync(path.join(outputRoot, 'lua'))).toBe(false);
      expect(fs.existsSync(path.join(outputRoot, 'legacy'))).toBe(false);
      expect(fs.existsSync(path.join(outputRoot, 'dist'))).toBe(false);
    });
  });
});

function createSyntheticModuleTablePlan(): RisuLuaSplitPlan {
  return {
    version: 1,
    mode: 'module-table',
    sourceProfile: 'plain-single',
    sourceProfileSummary: {
      profile: 'plain-single',
      confidence: 'high',
      reasons: ['Selected profile: plain-single.'],
      preloadModuleCount: 0,
      sectionMarkerCount: 0,
      staticRequireCount: 0,
      dynamicRequireCount: 0,
    },
    sourcePath: path.join(process.cwd(), 'fixtures/source.risulua'),
    targetName: 'source',
    entryPath: 'lua/main.risulua',
    distPath: null,
    packable: false,
    buildStrategy: 'report-only',
    files: [],
    risks: [],
    detectedRoots: [
      { name: 'onOutput', kind: 'function', sourceRange: sourceRange(20, 28, 300, 450) },
    ],
    hostApiSummary: {
      reads: ['getState', 'getChatVar'],
      writes: ['setState'],
      asyncCalls: ['LLM', 'request'],
      unknownGlobals: ['_G'],
    },
  };
}

function createSyntheticRefactorMap(): RisuLuaModuleTableRefactorMapContract {
  return {
    version: 1,
    mode: 'module-table',
    sourceFile: path.join(process.cwd(), 'fixtures/source.risulua'),
    modules: [
      {
        path: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
        requireId: 'common.local_helpers',
        alias: '__local_helpers',
        category: 'common-helper',
        exports: ['trim'],
      },
      {
        path: 'lua/handler_helpers/output_helpers.risulua',
        requireId: 'handler_helpers.output_helpers',
        alias: '__output_helpers',
        category: 'handler-helper',
        exports: ['normalizeOutput'],
      },
      {
        path: RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
        requireId: 'host_globals.global_functions',
        alias: '__host_globals',
        category: 'host-global',
        exports: ['onOutput'],
      },
      {
        path: RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
        requireId: 'host_globals.async_actions',
        alias: '__async_actions',
        category: 'host-global',
        exports: ['runModel'],
      },
    ],
    symbols: [
      {
        id: 'symbol:common:trim',
        originalName: 'trim',
        declarationKind: 'top-level-local-function',
        sourceRange: sourceRange(3, 5, 20, 78),
        classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
        exportName: 'trim',
        globalBridge: false,
        captures: [],
        mutates: [],
        hostEffects: createEmptyRisuLuaModuleTableHostEffects(),
        rewriteRefs: ['onOutput:24'],
      },
      {
        id: 'symbol:handler:normalizeOutput',
        originalName: 'normalizeOutput',
        declarationKind: 'nested-local-function',
        sourceRange: sourceRange(12, 14, 120, 198),
        parent: { kind: 'handler', name: 'onOutput', startLine: 20 },
        classification: 'extract:parameterized-read-helper',
        targetModule: 'lua/handler_helpers/output_helpers.risulua',
        exportName: 'normalizeOutput',
        globalBridge: false,
        captures: ['triggerId'],
        mutates: [],
        hostEffects: { ...createEmptyRisuLuaModuleTableHostEffects(), reads: ['getState'] },
        rewriteRefs: ['onOutput:25'],
      },
      {
        id: 'symbol:global:onOutput',
        originalName: 'onOutput',
        declarationKind: 'top-level-global-function',
        sourceRange: sourceRange(20, 28, 300, 450),
        classification: 'bridge:host-visible-global',
        targetModule: RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
        exportName: 'onOutput',
        globalBridge: true,
        bridge: {
          required: true,
          kind: 'direct_assignment',
          originalPublicName: 'onOutput',
          moduleAlias: '__host_globals',
          exportName: 'onOutput',
          mainAssignment: {
            shape: 'direct_assignment',
            text: 'onOutput = __host_globals.onOutput',
          },
        },
        captures: [],
        mutates: [],
        hostEffects: {
          ...createEmptyRisuLuaModuleTableHostEffects(),
          reads: ['getChatVar'],
          writes: ['setState'],
          uiInteraction: ['reloadDisplay'],
        },
        rewriteRefs: [],
      },
      {
        id: 'symbol:host:runModel',
        originalName: 'runModel',
        declarationKind: 'top-level-global-function',
        sourceRange: sourceRange(30, 36, 480, 610),
        classification: 'extract:host-read-helper',
        targetModule: RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
        exportName: 'runModel',
        globalBridge: false,
        captures: [],
        mutates: [],
        hostEffects: { ...createEmptyRisuLuaModuleTableHostEffects(), asyncModelNetwork: ['LLM', 'request'] },
        rewriteRefs: ['onOutput:27'],
      },
      {
        id: 'symbol:procedural:init',
        originalName: 'proceduralInit',
        declarationKind: 'procedural-block',
        sourceRange: sourceRange(38, 39, 612, 650),
        classification: 'preserve:top-level-side-effect',
        globalBridge: false,
        captures: [],
        mutates: [],
        hostEffects: {
          ...createEmptyRisuLuaModuleTableHostEffects(),
          uiInteraction: ['alertNormal'],
          dynamicEnvironment: ['load'],
        },
        rewriteRefs: [],
      },
      {
        id: 'symbol:domain:deck',
        originalName: 'DeckScore',
        declarationKind: 'domain-candidate',
        sourceRange: sourceRange(42, 46, 690, 840),
        classification: 'report:domain-candidate',
        globalBridge: false,
        captures: [],
        mutates: [],
        hostEffects: createEmptyRisuLuaModuleTableHostEffects(),
        rewriteRefs: [],
      },
    ],
    preserved: [
      {
        id: 'symbol:unsafe:rerollChoices',
        originalName: 'rerollChoices',
        sourceRange: sourceRange(52, 60, 900, 1120),
        reason: 'preserve:host-visible-global-unsafe-bridge',
        evidence: ['dynamic _G lookup nearby', 'async boundary cannot be proven safe'],
      },
      {
        id: 'symbol:unsafe:dynamicRequire',
        originalName: 'loadDynamicFeature',
        sourceRange: sourceRange(62, 66, 1140, 1240),
        reason: 'preserve:async-boundary-risk',
        evidence: ['network request controls callback order'],
      },
    ],
    domainCandidates: [
      {
        name: 'deck',
        sourceSymbols: ['DeckScore'],
        sourceRanges: [sourceRange(42, 46, 690, 840)],
        confidence: 0.82,
        evidence: ['symbol name contains Deck', 'state key cluster deck.*'],
        recommendedPath: 'lua/domain/deck.risulua',
        generationStatus: 'report-only',
        generationBlockedReasons: ['Domain generation is report-only by default.'],
        hostEffects: { ...createEmptyRisuLuaModuleTableHostEffects(), dynamicEnvironment: ['_G'] },
        notGeneratedReason: 'Domain grouping is report-only in the module-table MVP.',
        autoGenerated: false,
      },
    ],
  };
}

function sourceRange(startLine: number, endLine: number, startOffset: number, endOffset: number): LuaSourceRange {
  return { startLine, endLine, startOffset, endOffset };
}

function withTempDir(run: (outputRoot: string) => void): void {
  const outputRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'risulua-module-table-rendering-'));
  try {
    run(outputRoot);
  } finally {
    fs.rmSync(outputRoot, { recursive: true, force: true });
  }
}
