import { describe, expect, it } from 'vitest';

import {
  RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
  RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
  RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
  RISULUA_MODULE_TABLE_RUNTIME_OUTPUT_PATH,
  RISULUA_MODULE_TABLE_RUNTIME_START_PATH,
  createEmptyRisuLuaModuleTableHostEffects,
  parseRisuLuaModuleTableSource,
  validateDryRunEditPlan,
  validateWriterParity,
  validateRisuLuaModuleTableRefactorMap,
  type RisuLuaModuleTableRefactorMapContract,
} from '../src/domain/risulua-split';
import type { LuaSourceRange } from '../src/domain/risulua-split';
import {
  lines,
  planFixture,
  createSyntheticRefactorMapWithOverlap,
  createSyntheticOverlappingEditPlan,
} from './helpers/module-table-refactor-map-helpers';
import { createRisuLuaDomainGroupingContext } from '../src/domain/risulua-split/module-table/module-table-domain-grouping';

describe('risulua-split module-table dry-run refactor-map planner', () => {
  it('emits complete refactor-map and edit plan for a mixed fixture', async () => {
    const result = await planFixture(lines([
      'local function helperTrim(value)',
      '  return value:gsub("^%s+", "")',
      'end',
      '',
      'function setLanguage1(lang)',
      '  return helperTrim(lang)',
      'end',
      '',
      'setHeroineClothes = async(function(clothes)',
      '  alertNormal(clothes)',
      'end)',
      '',
      'local changedVars = { count = 0 }',
      'function onOutput(text)',
      '  local function pureDecorate(value)',
      '    return string.lower(value)',
      '  end',
      '  local function mutateTable()',
      '    changedVars.count = changedVars.count + 1',
      '  end',
      '  return pureDecorate(text)',
      'end',
      '',
      'local outside = 0',
      'local function bumpOutside()',
      '  outside = outside + 1',
      'end',
      '',
      'local function scoreDeck(cards)',
      '  return #cards * 10',
      'end',
    ]));

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    expect(result.refactorMap.modules.map((m) => m.path)).toEqual(expect.arrayContaining([
      RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
      RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
      RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
      RISULUA_MODULE_TABLE_RUNTIME_OUTPUT_PATH,
      'lua/handler_helpers/output_helpers.risulua',
    ]));

    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'helperTrim', classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'setLanguage1', classification: 'extract:host-global-function',
        targetModule: RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH, globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'setHeroineClothes', classification: 'extract:host-global-function',
        targetModule: RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH, globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'onOutput', classification: 'extract:runtime-handler-body',
        targetModule: RISULUA_MODULE_TABLE_RUNTIME_OUTPUT_PATH, globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'pureDecorate', classification: 'extract:pure-helper',
        targetModule: 'lua/handler_helpers/output_helpers.risulua', globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'scoreDeck', classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
      }),
    ]));

    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'mutateTable', reason: 'preserve:captured-table-mutation' }),
      expect.objectContaining({ originalName: 'bumpOutside', reason: 'preserve:captures-mutable-state' }),
    ]));

    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'bumpOutside', autoGenerated: false,
        recommendedPath: 'lua/domain/bump_outside.risulua',
      }),
      expect.objectContaining({
        name: 'scoreDeck', autoGenerated: false,
        recommendedPath: 'lua/domain/score_deck.risulua',
      }),
    ]));

    const extractEdits = result.editPlan.edits.filter((e) => e.intent === 'extract-symbol');
    const bridgeEdits = result.editPlan.edits.filter((e) => e.intent === 'bridge-global');
    const preserveEdits = result.editPlan.edits.filter(
      (e) => e.intent === 'preserve-in-main' || e.intent === 'preserve-procedural-root' || e.intent === 'preserve-handler-root',
    );
    expect(extractEdits.length).toBeGreaterThanOrEqual(2);
    expect(bridgeEdits.length).toBe(0);
    expect(preserveEdits.length).toBeGreaterThanOrEqual(2);

    expect(result.editPlan.mainBridgeInsertions).toEqual([]);
    expect(result.editPlan.mainRequireBindings.length).toBeGreaterThanOrEqual(3);
    expect(result.editPlan.mainRequireBindings).toEqual(expect.arrayContaining([
      expect.objectContaining({ alias: '__local_helpers' }),
      expect.objectContaining({ alias: '__host_globals' }),
      expect.objectContaining({ alias: '__async_actions' }),
      expect.objectContaining({ alias: '__runtime_output' }),
    ]));

    expect(result.validation.ok).toBe(true);
    expect(result.validation.findings).toEqual([]);

    for (const symbol of result.refactorMap.symbols) {
      if (symbol.classification.startsWith('extract:') || symbol.classification === 'bridge:host-visible-global') {
        expect(symbol.targetModule).toBeDefined();
        expect(symbol.exportName).toBeDefined();
        expect(symbol.sourceRange.endOffset).toBeGreaterThan(symbol.sourceRange.startOffset);
      }
    }
    for (const symbol of result.refactorMap.symbols) {
      if (symbol.globalBridge) {
        expect(symbol.bridge!.required).toBe(true);
        expect(symbol.bridge!.kind).toBe('direct_assignment');
      }
    }
    for (const p of result.refactorMap.preserved) {
      expect(p.evidence.length).toBeGreaterThan(0);
      expect(p.sourceRange.startOffset).toBeGreaterThanOrEqual(0);
    }
    for (const c of result.refactorMap.domainCandidates) {
      expect(c.autoGenerated).toBe(false);
    }
  });

  it('emits no workspace files — dry-run only', async () => {
    const result = await planFixture(lines([
      'local function helper() return 1 end',
      'function setLanguage1(lang) return helper() end',
      'function onOutput(text) return text end',
    ]));
    expect(result.ok).toBe(true);
    expect(typeof result.refactorMap).toBe('object');
    expect(Array.isArray(result.editPlan.edits)).toBe(true);
  });

  it('validates overlapping edits fail closed', async () => {
    const refactorMap = createSyntheticRefactorMapWithOverlap();
    const editPlan = createSyntheticOverlappingEditPlan();
    const parseResult = await parseRisuLuaModuleTableSource('function foo() return 1 end\n');
    const validation = validateDryRunEditPlan(editPlan, refactorMap, parseResult);
    expect(validation.ok).toBe(false);
    expect(validation.findings).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'overlapping-edits' }),
    ]));
  });

  it('validates edits inside comments/strings are rejected', async () => {
    const source = lines([
      '-- function fakeHelper() return 1 end',
      'local msg = "function fakeHelper2() return 2 end"',
      'local function realHelper() return 3 end',
    ]);
    const parseResult = await parseRisuLuaModuleTableSource(source);
    expect(parseResult.ok).toBe(true);
    expect(parseResult.nonExecutableRanges.length).toBeGreaterThan(0);

    const nonExec = parseResult.nonExecutableRanges[0];
    const fakeRange: LuaSourceRange = {
      startLine: nonExec.sourceRange.startLine, endLine: nonExec.sourceRange.endLine,
      startOffset: nonExec.sourceRange.startOffset, endOffset: nonExec.sourceRange.endOffset,
    };
    const refactorMap: RisuLuaModuleTableRefactorMapContract = {
      version: 1, mode: 'module-table', sourceFile: 'test.risulua',
      modules: [{ path: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, requireId: 'common.local_helpers', alias: '__local_helpers', category: 'common-helper', exports: ['fakeHelper'] }],
      symbols: [{ id: 'symbol:fake', originalName: 'fakeHelper', declarationKind: 'top-level-local-function', sourceRange: fakeRange, classification: 'extract:pure-helper', targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, exportName: 'fakeHelper', globalBridge: false, captures: [], mutates: [], hostEffects: createEmptyRisuLuaModuleTableHostEffects(), rewriteRefs: [] }],
      preserved: [], domainCandidates: [],
    };
    const editPlan = {
      edits: [{ id: 'edit:move:symbol:fake', intent: 'extract-symbol' as const, symbolId: 'symbol:fake', symbolName: 'fakeHelper', sourceRange: fakeRange, targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, classification: 'extract:pure-helper' as const }],
      moduleContracts: refactorMap.modules, mainPreservedRanges: [], mainBridgeInsertions: [], mainRequireBindings: [],
    };
    const validation = validateDryRunEditPlan(editPlan, refactorMap, parseResult);
    expect(validation.ok).toBe(false);
    expect(validation.findings).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'edit-inside-non-executable' }),
    ]));
  });

  it('rejects writer parity for artifacts absent from dry-run map', async () => {
    const result = await planFixture(lines([
      'local function helper() return 1 end',
      'function onOutput(text) return helper() end',
    ]));
    expect(validateWriterParity(RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, result.refactorMap)).toBeNull();
    expect(validateWriterParity('lua/main.risulua', result.refactorMap)).toBeNull();
    expect(validateWriterParity('legacy/original.risulua', result.refactorMap)).toBeNull();
    expect(validateWriterParity('docs/refactor-map.json', result.refactorMap)).toBeNull();
    expect(validateWriterParity('docs/domain-candidates.json', result.refactorMap)).toBeNull();

    const forbidden = validateWriterParity('lua/features/output_helpers.risulua', result.refactorMap);
    expect(forbidden).not.toBeNull();
    expect(forbidden!.code).toBe('forbidden-target-path');

    const domain = validateWriterParity('lua/domain/deck.risulua', result.refactorMap);
    expect(domain).not.toBeNull();
    expect(domain!.code).toBe('missing-refactor-map-entry');

    const missing = validateWriterParity('lua/handler_helpers/start_helpers.risulua', result.refactorMap);
    expect(missing).not.toBeNull();
    expect(missing!.code).toBe('missing-refactor-map-entry');

    const unknown = validateWriterParity('lua/unknown/module.risulua', result.refactorMap);
    expect(unknown).not.toBeNull();
    expect(unknown!.code).toBe('missing-refactor-map-entry');
  });

  it('rejects forbidden MVP target paths in edit plan', async () => {
    const refactorMap: RisuLuaModuleTableRefactorMapContract = {
      version: 1, mode: 'module-table', sourceFile: 'test.risulua',
      modules: [{ path: 'lua/features/output_helpers.risulua', requireId: 'features.output_helpers', alias: '__output_helpers', category: 'handler-helper', exports: ['badHelper'] }],
      symbols: [{ id: 'symbol:bad', originalName: 'badHelper', declarationKind: 'nested-local-function', sourceRange: { startLine: 1, endLine: 2, startOffset: 0, endOffset: 50 }, classification: 'extract:pure-helper', targetModule: 'lua/features/output_helpers.risulua', exportName: 'badHelper', globalBridge: false, captures: [], mutates: [], hostEffects: createEmptyRisuLuaModuleTableHostEffects(), rewriteRefs: [] }],
      preserved: [], domainCandidates: [],
    };
    const editPlan = {
      edits: [{ id: 'edit:move:symbol:bad', intent: 'extract-symbol' as const, symbolId: 'symbol:bad', symbolName: 'badHelper', sourceRange: { startLine: 1, endLine: 2, startOffset: 0, endOffset: 50 }, targetModule: 'lua/features/output_helpers.risulua', classification: 'extract:pure-helper' as const }],
      moduleContracts: refactorMap.modules, mainPreservedRanges: [], mainBridgeInsertions: [], mainRequireBindings: [],
    };
    const parseResult = await parseRisuLuaModuleTableSource('function foo() return 1 end\n');
    const validation = validateDryRunEditPlan(editPlan, refactorMap, parseResult);
    expect(validation.ok).toBe(false);
    expect(validation.findings).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'forbidden-target-path' }),
    ]));
  });

  it('preserves procedural blocks and roots with reason codes and source ranges', async () => {
    const result = await planFixture(lines([
      'local function helper() return 1 end',
      '',
      'function onOutput(text)',
      '  return helper(text)',
      'end',
      '',
      'function onStart()',
      '  local x = getChatVar("init")',
      '  alertNormal(x)',
      'end',
      '',
      'listenEdit(function(state)',
      '  state.changed = true',
      'end)',
    ]));
    const rootPreserved = result.refactorMap.preserved.filter(
      (e) => e.reason === 'preserve:top-level-side-effect',
    );
    expect(rootPreserved.length).toBeGreaterThanOrEqual(1);
    for (const entry of rootPreserved) {
      expect(entry.sourceRange.endOffset).toBeGreaterThan(entry.sourceRange.startOffset);
      expect(entry.evidence.length).toBeGreaterThan(0);
    }
    expect(result.validation.ok).toBe(true);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'onOutput', targetModule: RISULUA_MODULE_TABLE_RUNTIME_OUTPUT_PATH }),
      expect.objectContaining({ originalName: 'onStart', targetModule: RISULUA_MODULE_TABLE_RUNTIME_START_PATH }),
    ]));
  });

  it('validates domain candidates have autoGenerated false and no artifact edit', async () => {
    const result = await planFixture(lines([
      'local function scoreDeck(cards)',
      '  return #cards * 10',
      'end',
      'function onOutput(text) return scoreDeck({}) end',
    ]));
    expect(result.refactorMap.domainCandidates.length).toBeGreaterThan(0);
    for (const c of result.refactorMap.domainCandidates) {
      expect(c.autoGenerated).toBe(false);
      expect(c.generationStatus).toBe('report-only');
      expect(c.notGeneratedReason).toBeDefined();
      expect(c.sourceRanges.length).toBeGreaterThan(0);
    }
    for (const m of result.refactorMap.modules) expect(m.path).not.toMatch(/^lua\/domain\//);
    for (const e of result.editPlan.edits) expect(e.targetModule).not.toMatch(/^lua\/domain\//);
    expect(result.validation.ok).toBe(true);
  });

  it('promotes safe domain candidates to generated function modules when validated generation is requested', async () => {
    const result = await planFixture(lines([
      'local function scoreDeck(cards)',
      '  return #cards * 10',
      'end',
      'function onOutput(text) return scoreDeck({}) end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.domainGeneration).toBe('validated');
    expect(result.refactorMap.domainCandidates).toEqual([
      expect.objectContaining({
        name: 'scoreDeck',
        generationStatus: 'generated',
        generatedPath: 'lua/domain/score_deck.risulua',
        autoGenerated: true,
        grouping: expect.objectContaining({
          reason: 'singleton',
          path: 'lua/domain/score_deck.risulua',
          peers: ['scoreDeck'],
        }),
      }),
    ]);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'scoreDeck',
        classification: 'extract:domain-function',
        targetModule: 'lua/domain/score_deck.risulua',
      }),
    ]));
    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({
        path: 'lua/domain/score_deck.risulua',
        category: 'domain-function',
        alias: '__domain_score_deck',
      }),
    ]));
    expect(validateWriterParity('lua/domain/score_deck.risulua', result.refactorMap)).toBeNull();
    expect(result.validation.ok).toBe(true);
  });

  it('blocks private-table domain generation for reassigned domain function names', async () => {
    const result = await planFixture(lines([
      'local function computeValue(value)',
      '  return value + 1',
      'end',
      '',
      'computeValue = function(value)',
      '  return value + 2',
      'end',
      '',
      'function onOutput(text)',
      '  return tostring(computeValue(tonumber(text) or 0))',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.symbols).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'computeValue', classification: 'extract:domain-function' }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'computeValue',
        generationStatus: 'blocked',
        autoGenerated: false,
        generationBlockedReasons: expect.arrayContaining([
          'Blocked computeValue from private-table domain generation because reassignment was found at top level.',
        ]),
      }),
    ]));
  });

  it('blocks private-table domain generation for top-level eager calls', async () => {
    const result = await planFixture(lines([
      'local function computeValue(value)',
      '  return value + 1',
      'end',
      '',
      'local eagerValue = computeValue(1)',
      '',
      'function onOutput(text)',
      '  return tostring(eagerValue)',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.symbols).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'computeValue', classification: 'extract:domain-function' }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'computeValue',
        generationStatus: 'blocked',
        autoGenerated: false,
        generationBlockedReasons: expect.arrayContaining([
          'Blocked computeValue from private-table domain generation because a top-level eager call was found.',
        ]),
      }),
    ]));
  });

  it('blocks private-table domain generation for top-level function-value capture', async () => {
    const result = await planFixture(lines([
      'local function computeValue(value)',
      '  return value + 1',
      'end',
      '',
      'local callbacks = { computeValue }',
      '',
      'function onOutput(text)',
      '  return tostring(callbacks[1](tonumber(text) or 0))',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.symbols).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'computeValue', classification: 'extract:domain-function' }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'computeValue',
        generationStatus: 'blocked',
        autoGenerated: false,
        generationBlockedReasons: expect.arrayContaining([
          'Blocked computeValue from private-table domain generation because a top-level function-value capture was found.',
        ]),
      }),
    ]));
  });

  it('emits one refactor-map module contract for grouped domain candidates', async () => {
    const result = await planFixture(lines([
      'local function normalizeDeck(cards)',
      '  return cards or {}',
      'end',
      '',
      'local function scoreDeck(cards)',
      '  return #normalizeDeck(cards) * 10',
      'end',
      '',
      'function onOutput(text)',
      '  return tostring(scoreDeck({ text }))',
      'end',
    ]), { domainGeneration: 'validated' });

    const deckModules = result.refactorMap.modules.filter((moduleContract) => moduleContract.path === 'lua/domain/deck.risulua');
    expect(deckModules).toHaveLength(1);
    expect(deckModules[0]).toEqual(expect.objectContaining({
      path: 'lua/domain/deck.risulua',
      requireId: 'domain.deck',
      category: 'domain-function',
      alias: '__domain_deck',
      exports: expect.arrayContaining(['normalizeDeck', 'scoreDeck']),
    }));

    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'normalizeDeck',
        classification: 'extract:domain-function',
        targetModule: 'lua/domain/deck.risulua',
      }),
      expect.objectContaining({
        originalName: 'scoreDeck',
        classification: 'extract:domain-function',
        targetModule: 'lua/domain/deck.risulua',
      }),
    ]));

    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'normalizeDeck',
        recommendedPath: 'lua/domain/deck.risulua',
        grouping: expect.objectContaining({
          reason: 'repeated-token',
          path: 'lua/domain/deck.risulua',
          token: 'deck',
          peers: ['normalizeDeck', 'scoreDeck'],
        }),
      }),
      expect.objectContaining({
        name: 'scoreDeck',
        recommendedPath: 'lua/domain/deck.risulua',
        grouping: expect.objectContaining({
          reason: 'repeated-token',
          path: 'lua/domain/deck.risulua',
          token: 'deck',
          peers: ['normalizeDeck', 'scoreDeck'],
        }),
      }),
    ]));

    expect(result.editPlan.edits).toEqual(expect.arrayContaining([
      expect.objectContaining({
        symbolName: 'normalizeDeck',
        targetModule: 'lua/domain/deck.risulua',
      }),
      expect.objectContaining({
        symbolName: 'scoreDeck',
        targetModule: 'lua/domain/deck.risulua',
      }),
    ]));
    expect(validateWriterParity('lua/domain/deck.risulua', result.refactorMap)).toBeNull();
    expect(result.validation.ok).toBe(true);
  });

  it('groups singular and plural block helpers into one refactor-map module', async () => {
    const result = await planFixture(lines([
      'local function parseStoryChoiceBlock(text)',
      '  return text:gsub("Story", "")',
      'end',
      '',
      'local function parseStoryChoiceBlocks(text)',
      '  return parseStoryChoiceBlock(text) .. "|all"',
      'end',
      '',
      'function onOutput(text)',
      '  return parseStoryChoiceBlocks(text)',
      'end',
    ]), { domainGeneration: 'validated' });

    const blockModules = result.refactorMap.modules.filter((moduleContract) => moduleContract.path === 'lua/domain/story_choice_block.risulua');
    expect(blockModules).toHaveLength(1);
    expect(blockModules[0]).toEqual(expect.objectContaining({
      requireId: 'domain.story_choice_block',
      category: 'domain-function',
      alias: '__domain_story_choice_block',
      exports: expect.arrayContaining(['parseStoryChoiceBlock', 'parseStoryChoiceBlocks']),
    }));
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'parseStoryChoiceBlock', targetModule: 'lua/domain/story_choice_block.risulua' }),
      expect.objectContaining({ originalName: 'parseStoryChoiceBlocks', targetModule: 'lua/domain/story_choice_block.risulua' }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'parseStoryChoiceBlock',
        grouping: expect.objectContaining({ reason: 'normalized-token', token: 'story_choice_block' }),
      }),
      expect.objectContaining({
        name: 'parseStoryChoiceBlocks',
        grouping: expect.objectContaining({ reason: 'normalized-token', token: 'story_choice_block' }),
      }),
    ]));
    expect(validateWriterParity('lua/domain/story_choice_block.risulua', result.refactorMap)).toBeNull();
    expect(result.validation.ok).toBe(true);
  });

  it('normalizes repeated singular and plural block tokens into one module', async () => {
    const result = await planFixture(lines([
      'local function parseDevelopmentBlocks(text)',
      '  return text or ""',
      'end',
      '',
      'local function parseEnhancementBlock(text)',
      '  return parseDevelopmentBlocks(text) .. "|enhance"',
      'end',
      '',
      'function onOutput(text)',
      '  return parseEnhancementBlock(text)',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({
        path: 'lua/domain/block.risulua',
        exports: expect.arrayContaining(['parseDevelopmentBlocks', 'parseEnhancementBlock']),
      }),
    ]));
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/blocks.risulua')).toBe(false);
    for (const name of ['parseDevelopmentBlocks', 'parseEnhancementBlock']) {
      expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
        expect.objectContaining({
          name,
          grouping: expect.objectContaining({ reason: 'repeated-token', token: 'block', path: 'lua/domain/block.risulua' }),
        }),
      ]));
    }
    expect(result.validation.ok).toBe(true);
  });

  it('groups sibling render singleton helpers into a render action module', async () => {
    const result = await planFixture(lines([
      'local function renderLog(log)',
      '  return table.concat(log or {}, "|")',
      'end',
      '',
      'local function renderPhaseButtons(state)',
      '  return state.phase or ""',
      'end',
      '',
      'local function renderNestKeeperPopup(state)',
      '  return renderLog(state.log) .. renderPhaseButtons(state)',
      'end',
      '',
      'function onOutput(text)',
      '  return renderNestKeeperPopup({ log = { text }, phase = "ready" })',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({
        path: 'lua/domain/render.risulua',
        exports: expect.arrayContaining(['renderLog', 'renderPhaseButtons', 'renderNestKeeperPopup']),
      }),
    ]));
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/render_log.risulua')).toBe(false);
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/render_phase_buttons.risulua')).toBe(false);
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/render_nest_keeper_popup.risulua')).toBe(false);
    for (const name of ['renderLog', 'renderPhaseButtons', 'renderNestKeeperPopup']) {
      expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
        expect.objectContaining({
          name,
          grouping: expect.objectContaining({ reason: 'action-family', family: 'render', path: 'lua/domain/render.risulua' }),
        }),
      ]));
    }
    expect(result.validation.ok).toBe(true);
  });

  it('groups small text utility helpers into one refactor-map module', async () => {
    const result = await planFixture(lines([
      'local function trimText(value)',
      '  return (value or ""):gsub("^%s+", ""):gsub("%s+$", "")',
      'end',
      '',
      'local function normalizeText(value)',
      '  return string.lower(trimText(value))',
      'end',
      '',
      'local function joinTextParts(parts)',
      '  return table.concat(parts, ",")',
      'end',
      '',
      'function onOutput(text)',
      '  return normalizeText(joinTextParts({ text }))',
      'end',
    ]), { domainGeneration: 'validated' });

    const textModules = result.refactorMap.modules.filter((moduleContract) => moduleContract.path === 'lua/domain/text.risulua');
    expect(textModules).toHaveLength(1);
    expect(textModules[0].exports).toEqual(expect.arrayContaining(['trimText', 'normalizeText', 'joinTextParts']));
    for (const name of ['trimText', 'normalizeText', 'joinTextParts']) {
      expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
        expect.objectContaining({ originalName: name, targetModule: 'lua/domain/text.risulua' }),
      ]));
      expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
        expect.objectContaining({
          name,
          grouping: expect.objectContaining({ reason: 'utility-family', family: 'text', path: 'lua/domain/text.risulua' }),
        }),
      ]));
    }
    expect(result.validation.ok).toBe(true);
  });

  it('routes lone text utility helpers to the stable text utility module', async () => {
    const result = await planFixture(lines([
      'local function trim(value)',
      '  return (value or ""):gsub("^%s+", ""):gsub("%s+$", "")',
      'end',
      '',
      'function onOutput(text)',
      '  return trim(text)',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: 'lua/domain/text.risulua', exports: ['trim'] }),
    ]));
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/trim.risulua')).toBe(false);
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'trim',
        grouping: expect.objectContaining({ reason: 'utility-family', family: 'text', path: 'lua/domain/text.risulua' }),
      }),
    ]));
    expect(result.validation.ok).toBe(true);
  });

  it('uses the last matching utility token when multiple utility families match', async () => {
    const result = await planFixture(lines([
      'local function toPercentText(value)',
      '  return tostring(value) .. "%"',
      'end',
      '',
      'function onOutput(text)',
      '  return toPercentText(tonumber(text) or 0)',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: 'lua/domain/text.risulua', exports: ['toPercentText'] }),
    ]));
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/to_percent_text.risulua')).toBe(false);
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'toPercentText',
        grouping: expect.objectContaining({ reason: 'utility-family', family: 'text', path: 'lua/domain/text.risulua' }),
      }),
    ]));
    expect(result.validation.ok).toBe(true);
  });

  it('routes array utility helpers to the stable array utility module', async () => {
    const result = await planFixture(lines([
      'local function arrayContains(arr, value)',
      '  for _, v in ipairs(arr or {}) do',
      '    if v == value then return true end',
      '  end',
      '  return false',
      'end',
      '',
      'function onOutput(text)',
      '  return arrayContains({ text }, "ok") and "yes" or "no"',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: 'lua/domain/array.risulua', exports: ['arrayContains'] }),
    ]));
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/array_contains.risulua')).toBe(false);
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'arrayContains',
        grouping: expect.objectContaining({ reason: 'utility-family', family: 'array', path: 'lua/domain/array.risulua' }),
      }),
    ]));
    expect(result.validation.ok).toBe(true);
  });

  it('routes initiative calculators to the stable number utility module', async () => {
    const result = await planFixture(lines([
      'local function calcInitiative(unit, isDefender)',
      '  local s = unit.stats or {}',
      '  local value = ((s.agi or 1) * 2) + (s.luk or 1) + math.random(1, 20)',
      '  return isDefender and (value + 2) or value',
      'end',
      '',
      'function onOutput(text)',
      '  return tostring(calcInitiative({ stats = { agi = 1, luk = 1 } }, text == "defender"))',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: 'lua/domain/number.risulua', exports: ['calcInitiative'] }),
    ]));
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/calc_initiative.risulua')).toBe(false);
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'calcInitiative',
        grouping: expect.objectContaining({ reason: 'utility-family', family: 'number', path: 'lua/domain/number.risulua' }),
      }),
    ]));
    expect(result.validation.ok).toBe(true);
  });

  it('restores safe utility-family members after broader cycle coalescing', () => {
    const grouping = createRisuLuaDomainGroupingContext([
      'buildHero',
      'calcInitiative',
      'clampInt',
    ], {
      dependencies: new Map([
        ['buildHero', ['calcInitiative', 'clampInt']],
        ['calcInitiative', []],
        ['clampInt', ['buildHero']],
      ]),
    });

    expect(grouping.groupingForName('calcInitiative')).toEqual(expect.objectContaining({
      reason: 'utility-family',
      family: 'number',
      path: 'lua/domain/number.risulua',
    }));
    expect(grouping.groupingForName('clampInt')).toEqual(expect.objectContaining({
      reason: 'cycle-coalesced',
      path: 'lua/domain/clamp.risulua',
    }));
  });

  it('does not restore utility-family members when that would recreate a module cycle', () => {
    const grouping = createRisuLuaDomainGroupingContext([
      'buildHero',
      'calcInitiative',
    ], {
      dependencies: new Map([
        ['buildHero', ['calcInitiative']],
        ['calcInitiative', ['buildHero']],
      ]),
    });

    expect(grouping.groupingForName('calcInitiative')).toEqual(expect.objectContaining({
      reason: 'cycle-coalesced',
      path: 'lua/domain/hero.risulua',
    }));
  });

  it('groups small numeric utility helpers into one refactor-map module', async () => {
    const result = await planFixture(lines([
      'local function clampNumber(value, minValue, maxValue)',
      '  return math.max(minValue, math.min(maxValue, value))',
      'end',
      '',
      'local function roundNumber(value)',
      '  return math.floor(value + 0.5)',
      'end',
      '',
      'local function normalizePercent(value)',
      '  return clampNumber(roundNumber(value), 0, 100)',
      'end',
      '',
      'function onOutput(text)',
      '  return tostring(normalizePercent(tonumber(text) or 0))',
      'end',
    ]), { domainGeneration: 'validated' });

    const numberModules = result.refactorMap.modules.filter((moduleContract) => moduleContract.path === 'lua/domain/number.risulua');
    expect(numberModules).toHaveLength(1);
    expect(numberModules[0]).toEqual(expect.objectContaining({
      requireId: 'domain.number',
      category: 'domain-function',
      alias: '__domain_number',
      exports: expect.arrayContaining(['clampNumber', 'roundNumber', 'normalizePercent']),
    }));
    for (const name of ['clampNumber', 'roundNumber', 'normalizePercent']) {
      expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
        expect.objectContaining({ originalName: name, targetModule: 'lua/domain/number.risulua' }),
      ]));
    }
    expect(result.validation.ok).toBe(true);
  });

  it('prefers numeric utility grouping over repeated clamp token grouping', async () => {
    const result = await planFixture(lines([
      'local function clampInt(value, minValue, maxValue)',
      '  return math.max(minValue, math.min(maxValue, value))',
      'end',
      '',
      'local function clampNonNegativeInt(value)',
      '  return clampInt(value, 0, 999)',
      'end',
      '',
      'function onOutput(text)',
      '  return tostring(clampNonNegativeInt(tonumber(text) or 0))',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: 'lua/domain/number.risulua', exports: expect.arrayContaining(['clampInt', 'clampNonNegativeInt']) }),
    ]));
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/clamp.risulua')).toBe(false);
    for (const name of ['clampInt', 'clampNonNegativeInt']) {
      expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
        expect.objectContaining({
          name,
          grouping: expect.objectContaining({ reason: 'utility-family', family: 'number', path: 'lua/domain/number.risulua' }),
        }),
      ]));
    }
    expect(result.validation.ok).toBe(true);
  });

  it('does not group unrelated small helpers into a generic utility bucket', async () => {
    const result = await planFixture(lines([
      'local function scoreDeck(cards)',
      '  return #cards * 10',
      'end',
      '',
      'local function formatName(name)',
      '  return tostring(name or "")',
      'end',
      '',
      'function onOutput(text)',
      '  return formatName(scoreDeck({ text }))',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: 'lua/domain/score_deck.risulua', exports: ['scoreDeck'] }),
      expect.objectContaining({ path: 'lua/domain/format_name.risulua', exports: ['formatName'] }),
    ]));
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/utils.risulua')).toBe(false);
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/text.risulua')).toBe(false);
    expect(result.validation.ok).toBe(true);
  });

  it('keeps unrelated one-way domain dependencies as separate refactor-map modules', async () => {
    const result = await planFixture(lines([
      'local function normalizeAlpha(value)',
      '  return value or ""',
      'end',
      '',
      'local function scoreBeta(value)',
      '  return #normalizeAlpha(value)',
      'end',
      '',
      'function onOutput(text)',
      '  return tostring(scoreBeta(text))',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({
        path: 'lua/domain/normalize_alpha.risulua',
        requireId: 'domain.normalize_alpha',
        exports: ['normalizeAlpha'],
      }),
      expect.objectContaining({
        path: 'lua/domain/score_beta.risulua',
        requireId: 'domain.score_beta',
        exports: ['scoreBeta'],
      }),
    ]));
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/alpha.risulua')).toBe(false);
    expect(result.refactorMap.modules.some((moduleContract) => moduleContract.path === 'lua/domain/beta.risulua')).toBe(false);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'normalizeAlpha',
        targetModule: 'lua/domain/normalize_alpha.risulua',
      }),
      expect.objectContaining({
        originalName: 'scoreBeta',
        targetModule: 'lua/domain/score_beta.risulua',
      }),
    ]));
    expect(result.validation.ok).toBe(true);
  });

  it('restores safe multi-member semantic clusters after broad cycle coalescing', () => {
    const grouping = createRisuLuaDomainGroupingContext([
      'acquirePerk',
      'syncPerkVars',
      'makeChoicePrompt',
      'executeChoiceReroll',
      'generateAndAppendChoices',
      'parseAndApplySaveString',
      'loadLatestStateFromHistory',
    ], {
      dependencies: new Map([
        ['acquirePerk', ['syncPerkVars']],
        ['syncPerkVars', ['makeChoicePrompt']],
        ['makeChoicePrompt', ['executeChoiceReroll']],
        ['executeChoiceReroll', ['generateAndAppendChoices']],
        ['generateAndAppendChoices', ['syncPerkVars']],
        ['parseAndApplySaveString', []],
        ['loadLatestStateFromHistory', ['parseAndApplySaveString']],
      ]),
    });

    expect(grouping.groupingForName('makeChoicePrompt')).toEqual(expect.objectContaining({
      reason: 'repeated-token',
      token: 'choice',
      path: 'lua/domain/choice.risulua',
      peers: ['executeChoiceReroll', 'generateAndAppendChoices', 'makeChoicePrompt'],
    }));
    expect(grouping.groupingForName('executeChoiceReroll')).toEqual(expect.objectContaining({
      reason: 'repeated-token',
      token: 'choice',
      path: 'lua/domain/choice.risulua',
      peers: ['executeChoiceReroll', 'generateAndAppendChoices', 'makeChoicePrompt'],
    }));
    expect(grouping.groupingForName('generateAndAppendChoices')).toEqual(expect.objectContaining({
      reason: 'repeated-token',
      token: 'choice',
      path: 'lua/domain/choice.risulua',
      peers: ['executeChoiceReroll', 'generateAndAppendChoices', 'makeChoicePrompt'],
    }));

    expect(grouping.groupingForName('parseAndApplySaveString')).toEqual(expect.objectContaining({
      reason: 'repeated-token',
      token: 'string',
      path: 'lua/domain/string.risulua',
      peers: ['loadLatestStateFromHistory', 'parseAndApplySaveString'],
    }));
    expect(grouping.groupingForName('loadLatestStateFromHistory')).toEqual(expect.objectContaining({
      reason: 'repeated-token',
      token: 'string',
      path: 'lua/domain/string.risulua',
      peers: ['loadLatestStateFromHistory', 'parseAndApplySaveString'],
    }));
  });

  it('refreshes cycle-coalesced metadata for every peer in a coalesced module group', async () => {
    const result = await planFixture(lines([
      'function getItemSortRank(key)',
      '  return getSortedShopItemKeys({ key })[1] or key',
      'end',
      '',
      'function getSortedShopItemKeys(items)',
      '  table.sort(items, function(a, b)',
      '    return getItemSortRank(a) > getItemSortRank(b)',
      '  end)',
      '  return items',
      'end',
      '',
      'function onOutput(text)',
      '  return table.concat(getSortedShopItemKeys({ "rare", "common" }), ",")',
      'end',
    ]), { domainGeneration: 'validated' });

    const peers = ['getItemSortRank', 'getSortedShopItemKeys'];
    for (const name of peers) {
      expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
        expect.objectContaining({
          name,
          recommendedPath: 'lua/domain/item.risulua',
          grouping: expect.objectContaining({
            reason: 'cycle-coalesced',
            path: 'lua/domain/item.risulua',
            peers,
          }),
        }),
      ]));
    }
    expect(result.validation.ok).toBe(true);
  });

  it('handles empty source with no eligible symbols', async () => {
    const result = await planFixture('');
    expect(result.refactorMap.symbols).toEqual([]);
    expect(result.refactorMap.preserved).toEqual([]);
    expect(result.refactorMap.modules).toEqual([]);
    expect(result.refactorMap.domainCandidates).toEqual([]);
    expect(result.editPlan.edits).toEqual([]);
    expect(result.validation.ok).toBe(true);
  });

  it('handles comment-only source with no executable candidates', async () => {
    const result = await planFixture(lines([
      '-- This is a comment',
      '--[[ block comment ]]--',
      'local msg = "string content"',
    ]));
    expect(result.refactorMap.symbols).toEqual([]);
    expect(result.validation.ok).toBe(true);
  });
});
