import { describe, expect, it } from 'vitest';

import {
  RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
  RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
  RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
  RISULUA_MODULE_TABLE_RUNTIME_OUTPUT_PATH,
  RISULUA_MODULE_TABLE_RUNTIME_START_PATH,
  createEmptyRisuLuaModuleTableHostEffects,
  parseRisuLuaModuleTableSource,
  validateDryRunEditPlan,
  validateWriterParity,
  validateRisuLuaModuleTableRefactorMap,
  type RisuLuaModuleTableRefactorMapContract,
} from '../src/domain/risulua-split';
import type { LuaSourceRange } from '../src/domain/risulua-split';
import {
  lines,
  planFixture,
  createSyntheticRefactorMapWithOverlap,
  createSyntheticOverlappingEditPlan,
} from './helpers/module-table-refactor-map-helpers';

describe('risulua-split module-table dry-run refactor-map planner', () => {
  it('emits complete refactor-map and edit plan for a mixed fixture', async () => {
    const result = await planFixture(lines([
      'local function helperTrim(value)',
      '  return value:gsub("^%s+", "")',
      'end',
      '',
      'function setLanguage1(lang)',
      '  return helperTrim(lang)',
      'end',
      '',
      'setHeroineClothes = async(function(clothes)',
      '  alertNormal(clothes)',
      'end)',
      '',
      'local changedVars = { count = 0 }',
      'function onOutput(text)',
      '  local function pureDecorate(value)',
      '    return string.lower(value)',
      '  end',
      '  local function mutateTable()',
      '    changedVars.count = changedVars.count + 1',
      '  end',
      '  return pureDecorate(text)',
      'end',
      '',
      'local outside = 0',
      'local function bumpOutside()',
      '  outside = outside + 1',
      'end',
      '',
      'local function scoreDeck(cards)',
      '  return #cards * 10',
      'end',
    ]));

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    expect(result.refactorMap.modules.map((m) => m.path)).toEqual(expect.arrayContaining([
      RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
      RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
      RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
      RISULUA_MODULE_TABLE_RUNTIME_OUTPUT_PATH,
      'lua/handler_helpers/output_helpers.risulua',
    ]));

    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'helperTrim', classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'setLanguage1', classification: 'extract:host-global-function',
        targetModule: RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH, globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'setHeroineClothes', classification: 'extract:host-global-function',
        targetModule: RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH, globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'onOutput', classification: 'extract:runtime-handler-body',
        targetModule: RISULUA_MODULE_TABLE_RUNTIME_OUTPUT_PATH, globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'pureDecorate', classification: 'extract:pure-helper',
        targetModule: 'lua/handler_helpers/output_helpers.risulua', globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'scoreDeck', classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
      }),
    ]));

    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'mutateTable', reason: 'preserve:captured-table-mutation' }),
      expect.objectContaining({ originalName: 'bumpOutside', reason: 'preserve:captures-mutable-state' }),
    ]));

    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'bumpOutside', autoGenerated: false,
        recommendedPath: 'lua/domain/bump_outside.risulua',
      }),
      expect.objectContaining({
        name: 'scoreDeck', autoGenerated: false,
        recommendedPath: 'lua/domain/score_deck.risulua',
      }),
    ]));

    const extractEdits = result.editPlan.edits.filter((e) => e.intent === 'extract-symbol');
    const bridgeEdits = result.editPlan.edits.filter((e) => e.intent === 'bridge-global');
    const preserveEdits = result.editPlan.edits.filter(
      (e) => e.intent === 'preserve-in-main' || e.intent === 'preserve-procedural-root' || e.intent === 'preserve-handler-root',
    );
    expect(extractEdits.length).toBeGreaterThanOrEqual(2);
    expect(bridgeEdits.length).toBe(0);
    expect(preserveEdits.length).toBeGreaterThanOrEqual(2);

    expect(result.editPlan.mainBridgeInsertions).toEqual([]);
    expect(result.editPlan.mainRequireBindings.length).toBeGreaterThanOrEqual(3);
    expect(result.editPlan.mainRequireBindings).toEqual(expect.arrayContaining([
      expect.objectContaining({ alias: '__local_helpers' }),
      expect.objectContaining({ alias: '__host_globals' }),
      expect.objectContaining({ alias: '__async_actions' }),
      expect.objectContaining({ alias: '__runtime_output' }),
    ]));

    expect(result.validation.ok).toBe(true);
    expect(result.validation.findings).toEqual([]);

    for (const symbol of result.refactorMap.symbols) {
      if (symbol.classification.startsWith('extract:') || symbol.classification === 'bridge:host-visible-global') {
        expect(symbol.targetModule).toBeDefined();
        expect(symbol.exportName).toBeDefined();
        expect(symbol.sourceRange.endOffset).toBeGreaterThan(symbol.sourceRange.startOffset);
      }
    }
    for (const symbol of result.refactorMap.symbols) {
      if (symbol.globalBridge) {
        expect(symbol.bridge!.required).toBe(true);
        expect(symbol.bridge!.kind).toBe('direct_assignment');
      }
    }
    for (const p of result.refactorMap.preserved) {
      expect(p.evidence.length).toBeGreaterThan(0);
      expect(p.sourceRange.startOffset).toBeGreaterThanOrEqual(0);
    }
    for (const c of result.refactorMap.domainCandidates) {
      expect(c.autoGenerated).toBe(false);
    }
  });

  it('emits no workspace files — dry-run only', async () => {
    const result = await planFixture(lines([
      'local function helper() return 1 end',
      'function setLanguage1(lang) return helper() end',
      'function onOutput(text) return text end',
    ]));
    expect(result.ok).toBe(true);
    expect(typeof result.refactorMap).toBe('object');
    expect(Array.isArray(result.editPlan.edits)).toBe(true);
  });

  it('validates overlapping edits fail closed', async () => {
    const refactorMap = createSyntheticRefactorMapWithOverlap();
    const editPlan = createSyntheticOverlappingEditPlan();
    const parseResult = await parseRisuLuaModuleTableSource('function foo() return 1 end\n');
    const validation = validateDryRunEditPlan(editPlan, refactorMap, parseResult);
    expect(validation.ok).toBe(false);
    expect(validation.findings).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'overlapping-edits' }),
    ]));
  });

  it('validates edits inside comments/strings are rejected', async () => {
    const source = lines([
      '-- function fakeHelper() return 1 end',
      'local msg = "function fakeHelper2() return 2 end"',
      'local function realHelper() return 3 end',
    ]);
    const parseResult = await parseRisuLuaModuleTableSource(source);
    expect(parseResult.ok).toBe(true);
    expect(parseResult.nonExecutableRanges.length).toBeGreaterThan(0);

    const nonExec = parseResult.nonExecutableRanges[0];
    const fakeRange: LuaSourceRange = {
      startLine: nonExec.sourceRange.startLine, endLine: nonExec.sourceRange.endLine,
      startOffset: nonExec.sourceRange.startOffset, endOffset: nonExec.sourceRange.endOffset,
    };
    const refactorMap: RisuLuaModuleTableRefactorMapContract = {
      version: 1, mode: 'module-table', sourceFile: 'test.risulua',
      modules: [{ path: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, requireId: 'common.local_helpers', alias: '__local_helpers', category: 'common-helper', exports: ['fakeHelper'] }],
      symbols: [{ id: 'symbol:fake', originalName: 'fakeHelper', declarationKind: 'top-level-local-function', sourceRange: fakeRange, classification: 'extract:pure-helper', targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, exportName: 'fakeHelper', globalBridge: false, captures: [], mutates: [], hostEffects: createEmptyRisuLuaModuleTableHostEffects(), rewriteRefs: [] }],
      preserved: [], domainCandidates: [],
    };
    const editPlan = {
      edits: [{ id: 'edit:move:symbol:fake', intent: 'extract-symbol' as const, symbolId: 'symbol:fake', symbolName: 'fakeHelper', sourceRange: fakeRange, targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, classification: 'extract:pure-helper' as const }],
      moduleContracts: refactorMap.modules, mainPreservedRanges: [], mainBridgeInsertions: [], mainRequireBindings: [],
    };
    const validation = validateDryRunEditPlan(editPlan, refactorMap, parseResult);
    expect(validation.ok).toBe(false);
    expect(validation.findings).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'edit-inside-non-executable' }),
    ]));
  });

  it('rejects writer parity for artifacts absent from dry-run map', async () => {
    const result = await planFixture(lines([
      'local function helper() return 1 end',
      'function onOutput(text) return helper() end',
    ]));
    expect(validateWriterParity(RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH, result.refactorMap)).toBeNull();
    expect(validateWriterParity('lua/main.risulua', result.refactorMap)).toBeNull();
    expect(validateWriterParity('legacy/original.risulua', result.refactorMap)).toBeNull();
    expect(validateWriterParity('docs/refactor-map.json', result.refactorMap)).toBeNull();
    expect(validateWriterParity('docs/domain-candidates.json', result.refactorMap)).toBeNull();

    const forbidden = validateWriterParity('lua/features/output_helpers.risulua', result.refactorMap);
    expect(forbidden).not.toBeNull();
    expect(forbidden!.code).toBe('forbidden-target-path');

    const domain = validateWriterParity('lua/domain/deck.risulua', result.refactorMap);
    expect(domain).not.toBeNull();
    expect(domain!.code).toBe('missing-refactor-map-entry');

    const missing = validateWriterParity('lua/handler_helpers/start_helpers.risulua', result.refactorMap);
    expect(missing).not.toBeNull();
    expect(missing!.code).toBe('missing-refactor-map-entry');

    const unknown = validateWriterParity('lua/unknown/module.risulua', result.refactorMap);
    expect(unknown).not.toBeNull();
    expect(unknown!.code).toBe('missing-refactor-map-entry');
  });

  it('rejects forbidden MVP target paths in edit plan', async () => {
    const refactorMap: RisuLuaModuleTableRefactorMapContract = {
      version: 1, mode: 'module-table', sourceFile: 'test.risulua',
      modules: [{ path: 'lua/features/output_helpers.risulua', requireId: 'features.output_helpers', alias: '__output_helpers', category: 'handler-helper', exports: ['badHelper'] }],
      symbols: [{ id: 'symbol:bad', originalName: 'badHelper', declarationKind: 'nested-local-function', sourceRange: { startLine: 1, endLine: 2, startOffset: 0, endOffset: 50 }, classification: 'extract:pure-helper', targetModule: 'lua/features/output_helpers.risulua', exportName: 'badHelper', globalBridge: false, captures: [], mutates: [], hostEffects: createEmptyRisuLuaModuleTableHostEffects(), rewriteRefs: [] }],
      preserved: [], domainCandidates: [],
    };
    const editPlan = {
      edits: [{ id: 'edit:move:symbol:bad', intent: 'extract-symbol' as const, symbolId: 'symbol:bad', symbolName: 'badHelper', sourceRange: { startLine: 1, endLine: 2, startOffset: 0, endOffset: 50 }, targetModule: 'lua/features/output_helpers.risulua', classification: 'extract:pure-helper' as const }],
      moduleContracts: refactorMap.modules, mainPreservedRanges: [], mainBridgeInsertions: [], mainRequireBindings: [],
    };
    const parseResult = await parseRisuLuaModuleTableSource('function foo() return 1 end\n');
    const validation = validateDryRunEditPlan(editPlan, refactorMap, parseResult);
    expect(validation.ok).toBe(false);
    expect(validation.findings).toEqual(expect.arrayContaining([
      expect.objectContaining({ code: 'forbidden-target-path' }),
    ]));
  });

  it('preserves procedural blocks and roots with reason codes and source ranges', async () => {
    const result = await planFixture(lines([
      'local function helper() return 1 end',
      '',
      'function onOutput(text)',
      '  return helper(text)',
      'end',
      '',
      'function onStart()',
      '  local x = getChatVar("init")',
      '  alertNormal(x)',
      'end',
      '',
      'listenEdit(function(state)',
      '  state.changed = true',
      'end)',
    ]));
    const rootPreserved = result.refactorMap.preserved.filter(
      (e) => e.reason === 'preserve:top-level-side-effect',
    );
    expect(rootPreserved.length).toBeGreaterThanOrEqual(1);
    for (const entry of rootPreserved) {
      expect(entry.sourceRange.endOffset).toBeGreaterThan(entry.sourceRange.startOffset);
      expect(entry.evidence.length).toBeGreaterThan(0);
    }
    expect(result.validation.ok).toBe(true);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'onOutput', targetModule: RISULUA_MODULE_TABLE_RUNTIME_OUTPUT_PATH }),
      expect.objectContaining({ originalName: 'onStart', targetModule: RISULUA_MODULE_TABLE_RUNTIME_START_PATH }),
    ]));
  });

  it('validates domain candidates have autoGenerated false and no artifact edit', async () => {
    const result = await planFixture(lines([
      'local function scoreDeck(cards)',
      '  return #cards * 10',
      'end',
      'function onOutput(text) return scoreDeck({}) end',
    ]));
    expect(result.refactorMap.domainCandidates.length).toBeGreaterThan(0);
    for (const c of result.refactorMap.domainCandidates) {
      expect(c.autoGenerated).toBe(false);
      expect(c.generationStatus).toBe('report-only');
      expect(c.notGeneratedReason).toBeDefined();
      expect(c.sourceRanges.length).toBeGreaterThan(0);
    }
    for (const m of result.refactorMap.modules) expect(m.path).not.toMatch(/^lua\/domain\//);
    for (const e of result.editPlan.edits) expect(e.targetModule).not.toMatch(/^lua\/domain\//);
    expect(result.validation.ok).toBe(true);
  });

  it('promotes safe domain candidates to generated function modules when validated generation is requested', async () => {
    const result = await planFixture(lines([
      'local function scoreDeck(cards)',
      '  return #cards * 10',
      'end',
      'function onOutput(text) return scoreDeck({}) end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.domainGeneration).toBe('validated');
    expect(result.refactorMap.domainCandidates).toEqual([
      expect.objectContaining({
        name: 'scoreDeck',
        generationStatus: 'generated',
        generatedPath: 'lua/domain/score_deck.risulua',
        autoGenerated: true,
      }),
    ]);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'scoreDeck',
        classification: 'extract:domain-function',
        targetModule: 'lua/domain/score_deck.risulua',
      }),
    ]));
    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({
        path: 'lua/domain/score_deck.risulua',
        category: 'domain-function',
        alias: '__domain_score_deck',
      }),
    ]));
    expect(validateWriterParity('lua/domain/score_deck.risulua', result.refactorMap)).toBeNull();
    expect(result.validation.ok).toBe(true);
  });

  it('handles empty source with no eligible symbols', async () => {
    const result = await planFixture('');
    expect(result.refactorMap.symbols).toEqual([]);
    expect(result.refactorMap.preserved).toEqual([]);
    expect(result.refactorMap.modules).toEqual([]);
    expect(result.refactorMap.domainCandidates).toEqual([]);
    expect(result.editPlan.edits).toEqual([]);
    expect(result.validation.ok).toBe(true);
  });

  it('handles comment-only source with no executable candidates', async () => {
    const result = await planFixture(lines([
      '-- This is a comment',
      '--[[ block comment ]]--',
      'local msg = "string content"',
    ]));
    expect(result.refactorMap.symbols).toEqual([]);
    expect(result.validation.ok).toBe(true);
  });
});
