import { describe, expect, it } from 'vitest';

import {
  RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
  RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
  RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
  analyzeRisuLuaModuleTable,
  classifyRisuLuaModuleTableDecisions,
  parseRisuLuaModuleTableSource,
  validateRisuLuaModuleTableRefactorMap,
  type RisuLuaModuleTableClassificationResult,
} from '../src/domain/risulua-split';

describe('risulua-split module-table classifier', () => {
  it('applies precedence so host-visible globals bridge before domain report-only proposals', async () => {
    const result = await classify(lines([
      'local function trimText(value)',
      '  return value:gsub("^%s+", "")',
      'end',
      '',
      'function DeckShuffle(cards)',
      '  return trimText(cards[1])',
      'end',
      '',
      'setHeroineClothes = async(function(clothes)',
      '  alertNormal(clothes)',
      'end)',
      '',
      'function onOutput(text)',
      '  return DeckShuffle({ text })',
      'end',
    ]));

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'trimText',
        classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
        globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'DeckShuffle',
        classification: 'bridge:host-visible-global',
        targetModule: RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
        globalBridge: true,
        bridge: expect.objectContaining({
          kind: 'direct_assignment',
          mainAssignment: { shape: 'direct_assignment', text: 'DeckShuffle = __host_globals.DeckShuffle' },
        }),
      }),
      expect.objectContaining({
        originalName: 'setHeroineClothes',
        classification: 'bridge:host-visible-global',
        targetModule: RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
        bridge: expect.objectContaining({
          mainAssignment: { shape: 'direct_assignment', text: 'setHeroineClothes = __async_actions.setHeroineClothes' },
        }),
      }),
    ]));
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'onOutput', reason: 'preserve:top-level-side-effect' }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual([
      expect.objectContaining({
        name: 'DeckShuffle',
        autoGenerated: false,
        recommendedPath: 'lua/domain/deck_shuffle.risulua',
      }),
    ]);
    expect(result.refactorMap.modules.map((moduleContract) => moduleContract.path)).not.toContain('lua/domain/deck_shuffle.risulua');
  });

  it('preserves unsafe public globals with exact conservative reason codes', async () => {
    const result = await classify(lines([
      'function dynamicPublic(name)',
      '  return _G[name]',
      'end',
      '',
      'function duplicatedGlobal() return 1 end',
      'function duplicatedGlobal() return 2 end',
      '',
      'function unknownDependency()',
      '  return missingGlobal()',
      'end',
      '',
      'function collidingExport() return 3 end',
      'collidingExport = { value = 4 }',
    ]));

    expect(result.refactorMap.symbols).toEqual([]);
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'dynamicPublic', reason: 'preserve:dynamic-global-reference-risk' }),
      expect.objectContaining({ originalName: 'duplicatedGlobal', reason: 'preserve:host-visible-global-unsafe-bridge' }),
      expect.objectContaining({ originalName: 'unknownDependency', reason: 'preserve:ambiguous' }),
      expect.objectContaining({ originalName: 'collidingExport', reason: 'preserve:host-visible-global-unsafe-bridge' }),
    ]));
  });

  it('extracts private top-level locals only when lexical facts are safe', async () => {
    const result = await classify(lines([
      'local function normalizeName(value)',
      '  return string.lower(value)',
      'end',
      '',
      'local function scoreDeck(cards)',
      '  return #cards * 10',
      'end',
      '',
      'local outside = 0',
      'local function bumpOutside()',
      '  outside = outside + 1',
      'end',
    ]));

    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'normalizeName',
        classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
      }),
      expect.objectContaining({
        originalName: 'scoreDeck',
        classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
      }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual([
      expect.objectContaining({
        name: 'scoreDeck',
        autoGenerated: false,
        recommendedPath: 'lua/domain/score_deck.risulua',
      }),
    ]);
    expect(result.refactorMap.modules.map((moduleContract) => moduleContract.path)).not.toContain('lua/domain/score_deck.risulua');
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'bumpOutside', reason: 'preserve:captures-mutable-state' }),
    ]));
  });

  it('classifies nested helpers as pure host-read parameterized or preserved unsafe', async () => {
    const result = await classify(lines([
      'local changedVars = { count = 0 }',
      'function onOutput(text)',
      '  local suffix = "!"',
      '  local function decorate(value)',
      '    return string.lower(value)',
      '  end',
      '  local function readMood(key)',
      '    return getChatVar(key)',
      '  end',
      '  local function appendSuffix(value)',
      '    return value .. suffix',
      '  end',
      '  local function mutateTable()',
      '    changedVars.count = changedVars.count + 1',
      '  end',
      '  local function writeHost()',
      '    setChatVar("last", text)',
      '  end',
      '  return decorate(text) .. readMood("mood") .. appendSuffix(text)',
      'end',
    ]));

    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'decorate', classification: 'extract:pure-helper', targetModule: 'lua/handler_helpers/output_helpers.risulua' }),
      expect.objectContaining({ originalName: 'readMood', classification: 'extract:host-read-helper', targetModule: 'lua/handler_helpers/output_helpers.risulua' }),
      expect.objectContaining({ originalName: 'appendSuffix', classification: 'extract:parameterized-read-helper', targetModule: 'lua/handler_helpers/output_helpers.risulua' }),
    ]));
    expect(result.parameterizedHelpers).toEqual([
      expect.objectContaining({ originalName: 'appendSuffix', capturedReads: ['suffix'], reason: 'handler-local-read-parameterized' }),
    ]);
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'mutateTable', reason: 'preserve:captured-table-mutation' }),
      expect.objectContaining({ originalName: 'writeHost', reason: 'preserve:host-write-order' }),
    ]));
  });
});

async function classify(source: string): Promise<RisuLuaModuleTableClassificationResult> {
  const parseResult = await parseRisuLuaModuleTableSource(source);
  const analyzerResult = analyzeRisuLuaModuleTable({ source, parseResult });
  expect(analyzerResult.ok).toBe(true);
  return classifyRisuLuaModuleTableDecisions({ source, sourceFile: 'legacy/original.risulua', analyzerResult });
}

function lines(sourceLines: string[]): string {
  return `${sourceLines.join('\n')}\n`;
}
