import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {
  analyzeRisuLuaModuleTable,
  classifyRisuLuaModuleTableDecisions,
  parseRisuLuaModuleTableSource,
  planDryRunRefactorMap,
  renderRisuLuaSplitReport,
  writeRisuLuaModuleTableDomainCandidates,
  writeRisuLuaModuleTableRefactorMap,
  writeRisuLuaSplitPlan,
  type RisuLuaSplitPlan,
} from '../src/domain/risulua-split';

const archiveRoot = path.resolve(process.cwd(), '..', '..', 'risulua-static-clean-refactor-review', 'examples');

const archiveExamples = [
  'chikan_train_original.risulua',
  'merry_sisters_final_original.risulua',
  'merry_rpg_module_original.risulua',
];
const archiveExamplesAvailable = archiveExamples.every((filename) => fs.existsSync(path.join(archiveRoot, filename)));
const describeArchiveExamples = archiveExamplesAvailable ? describe : describe.skip;

// Helper-level cache for Chikan analysis result to avoid duplicate analysis
// across the archive examples test and the block-comment listenEdit assertion.
let chikanAnalysisCache: Awaited<ReturnType<typeof analyzeArchiveReportOnly>> | null = null;
let chikanSourceCache: string | null = null;

describeArchiveExamples('risulua-split module-table archive report-only QA', () => {
  it('analyzes archive examples into report evidence without production lua output', async () => {
    for (const filename of archiveExamples) {
      const sourcePath = path.join(archiveRoot, filename);
      const source = fs.readFileSync(sourcePath, 'utf8');
      const qa = await analyzeArchiveReportOnly(source, sourcePath);

      // Cache Chikan analysis for reuse in the block-comment listenEdit assertion
      if (filename === 'chikan_train_original.risulua') {
        chikanAnalysisCache = qa;
        chikanSourceCache = source;
      }

      const outputRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'risulua-archive-report-only-'));

      try {
        writeReportOnlyEvidence(outputRoot, qa);

        expect(qa.dryRun.ok).toBe(true);
        expect(qa.dryRun.refactorMap.mode).toBe('module-table');
        expect(qa.dryRun.refactorMap.modules.every((module) => !module.path.startsWith('lua/domain/'))).toBe(true);
        expect(qa.dryRun.refactorMap.modules.every((module) => !/^lua\/features\/.+_helpers\.risulua$/.test(module.path))).toBe(true);
        expect(qa.dryRun.refactorMap.domainCandidates.every((candidate) => candidate.autoGenerated === false)).toBe(true);
        expect(fs.existsSync(path.join(outputRoot, 'docs', 'refactor-map.json'))).toBe(true);
        expect(fs.existsSync(path.join(outputRoot, 'docs', 'domain-candidates.json'))).toBe(true);
        expect(fs.existsSync(path.join(outputRoot, 'docs', 'risulua-split-plan.json'))).toBe(true);
        expect(fs.existsSync(path.join(outputRoot, 'docs', 'risulua-split-report.md'))).toBe(true);
        expect(fs.existsSync(path.join(outputRoot, 'lua'))).toBe(false);
        expect(fs.existsSync(path.join(outputRoot, 'legacy'))).toBe(false);
        expect(fs.existsSync(path.join(outputRoot, 'dist'))).toBe(false);
      } finally {
        fs.rmSync(outputRoot, { recursive: true, force: true });
      }
    }
  }, 180_000);

  it('ignores archive Chikan block-comment listenEdit as executable code', async () => {
    // Reuse cached Chikan analysis from the archive examples test to avoid duplicate analysis
    const sourcePath = path.join(archiveRoot, 'chikan_train_original.risulua');
    const source = chikanSourceCache ?? fs.readFileSync(sourcePath, 'utf8');
    const qa = chikanAnalysisCache ?? await analyzeArchiveReportOnly(source, sourcePath);

    expect(source).toContain('--[[\nlistenEdit("editDisplay"');
    expect(qa.analyzer.runtimeRoots.some((root) => root.name === 'listenEdit')).toBe(false);
    expect(qa.dryRun.refactorMap.symbols.some((symbol) => symbol.originalName === 'listenEdit')).toBe(false);
  }, 90_000);
});

async function analyzeArchiveReportOnly(source: string, sourcePath: string) {
  const parseResult = await parseRisuLuaModuleTableSource(source);
  expect(parseResult.ok).toBe(true);
  if (!parseResult.ok) throw new Error('archive parse failed');

  const analyzer = analyzeRisuLuaModuleTable({ source, parseResult });
  const classification = classifyRisuLuaModuleTableDecisions({ source, sourceFile: sourcePath, analyzerResult: analyzer });
  const dryRun = planDryRunRefactorMap({ source, sourceFile: sourcePath, parseResult, classificationResult: classification });
  const plan = createArchiveReportOnlyPlan(sourcePath, source, analyzer, dryRun.refactorMap.modules.map((module) => module.path));
  const report = renderRisuLuaSplitReport({
    plan,
    moduleTableRefactorMap: dryRun.refactorMap,
    profileMap: ['Archive module-table QA runs analyzer/refactor-map/report only.'],
    pureCandidates: [],
    runtimeCoupledHelpers: [],
    riskyBlocks: [],
    dynamicPatterns: [],
    refactorTasks: [],
    verificationSuggestions: ['Do not generate production lua/*, legacy/*, or dist/* from archive examples.'],
  });

  return { analyzer, dryRun, plan, report };
}

function writeReportOnlyEvidence(outputRoot: string, qa: Awaited<ReturnType<typeof analyzeArchiveReportOnly>>): void {
  const docsDir = path.join(outputRoot, 'docs');
  fs.mkdirSync(docsDir, { recursive: true });
  writeRisuLuaModuleTableRefactorMap(qa.dryRun.refactorMap, { outputRoot, cwd: process.cwd() });
  writeRisuLuaModuleTableDomainCandidates(qa.dryRun.refactorMap.domainCandidates, { outputRoot, cwd: process.cwd() });
  writeRisuLuaSplitPlan(qa.plan, { outputRoot, cwd: process.cwd() });
  fs.writeFileSync(path.join(docsDir, 'risulua-split-report.md'), qa.report, 'utf8');
}

function createArchiveReportOnlyPlan(
  sourcePath: string,
  source: string,
  analyzer: ReturnType<typeof analyzeRisuLuaModuleTable>,
  modulePaths: string[],
): RisuLuaSplitPlan {
  return {
    version: 1,
    mode: 'module-table',
    sourceProfile: 'plain-single',
    sourceProfileSummary: {
      profile: 'plain-single',
      confidence: 'high',
      reasons: ['Archive QA invokes module-table analyzer/report-only pipeline directly.'],
      preloadModuleCount: 0,
      sectionMarkerCount: 0,
      staticRequireCount: 0,
      dynamicRequireCount: 0,
    },
    sourcePath,
    targetName: path.basename(sourcePath, '.risulua'),
    entryPath: 'lua/main.risulua',
    distPath: null,
    packable: false,
    buildStrategy: 'report-only',
    files: modulePaths.map((modulePath, index) => ({
      path: modulePath,
      kind: 'coarse-block',
      sourceRanges: [{ startLine: 1, endLine: source.split('\n').length, startOffset: 0, endOffset: source.length }],
      confidence: 'medium',
      reason: 'Report-only archive QA module candidate; not written as production lua output.',
      preserveOrderIndex: index,
    })),
    risks: [],
    detectedRoots: analyzer.runtimeRoots.map((root) => ({
      name: root.name,
      kind: root.kind === 'listener-registration' ? 'listener' : root.kind === 'handler-function' ? 'function' : 'handler-assignment',
      sourceRange: root.sourceRange,
    })),
    hostApiSummary: {
      reads: analyzer.hostEffects.reads,
      writes: analyzer.hostEffects.writes,
      asyncCalls: analyzer.hostEffects.asyncModelNetwork,
      unknownGlobals: analyzer.hostEffects.dynamicEnvironment,
    },
  };
}
