import { describe, expect, it } from 'vitest';

import {
  RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
  RISULUA_MODULE_TABLE_BUTTON_ACTIONS_PATH,
  RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
  RISULUA_MODULE_TABLE_DUPLICATE_GLOBALS_PATH,
  RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
  RISULUA_MODULE_TABLE_RUNTIME_OUTPUT_PATH,
  analyzeRisuLuaModuleTable,
  classifyRisuLuaModuleTableDecisions,
  parseRisuLuaModuleTableSource,
  validateRisuLuaModuleTableRefactorMap,
  type RisuLuaModuleTableClassificationResult,
  type RisuLuaModuleTableDomainGenerationOption,
} from '../src/domain/risulua-split';

describe('risulua-split module-table classifier', () => {
  it('extracts strict host globals as module dependencies without main bridges', async () => {
    const result = await classify(lines([
      'local function trimText(value)',
      '  return value:gsub("^%s+", "")',
      'end',
      '',
      'function DeckShuffle(cards)',
      '  return trimText(cards[1])',
      'end',
      '',
      'setHeroineClothes = async(function(clothes)',
      '  alertNormal(clothes)',
      'end)',
      '',
      'function onOutput(text)',
      '  return DeckShuffle({ text })',
      'end',
    ]));

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'trimText',
        classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
        globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'DeckShuffle',
        classification: 'extract:host-global-function',
        targetModule: RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
        globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'setHeroineClothes',
        classification: 'extract:host-global-function',
        targetModule: RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
        globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'onOutput',
        classification: 'extract:runtime-handler-body',
        targetModule: RISULUA_MODULE_TABLE_RUNTIME_OUTPUT_PATH,
        globalBridge: false,
      }),
    ]));
    expect(result.refactorMap.preserved).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'onOutput' }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual([
      expect.objectContaining({
        name: 'DeckShuffle',
        autoGenerated: false,
        generationStatus: 'report-only',
        recommendedPath: 'lua/domain/deck_shuffle.risulua',
      }),
    ]);
    expect(result.refactorMap.modules.map((moduleContract) => moduleContract.path)).not.toContain('lua/domain/deck_shuffle.risulua');
  });

  it('bridges safe duplicate public globals with source-order versioned exports', async () => {
    const result = await classify(lines([
      'function duplicatedGlobal() return 1 end',
      'function duplicatedGlobal() return 2 end',
    ]));

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'duplicatedGlobal',
        targetModule: RISULUA_MODULE_TABLE_DUPLICATE_GLOBALS_PATH,
        exportName: 'duplicatedGlobal__L1',
        bridge: expect.objectContaining({
          mainAssignment: { shape: 'direct_assignment', text: 'duplicatedGlobal = __duplicate_globals.duplicatedGlobal__L1' },
        }),
      }),
      expect.objectContaining({
        originalName: 'duplicatedGlobal',
        targetModule: RISULUA_MODULE_TABLE_DUPLICATE_GLOBALS_PATH,
        exportName: 'duplicatedGlobal__L2',
        bridge: expect.objectContaining({
          mainAssignment: { shape: 'direct_assignment', text: 'duplicatedGlobal = __duplicate_globals.duplicatedGlobal__L2' },
        }),
      }),
    ]));
    expect(result.refactorMap.preserved).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'duplicatedGlobal' }),
    ]));
  });

  it('preserves unsafe public globals with exact conservative reason codes', async () => {
    const result = await classify(lines([
      'function dynamicPublic(name)',
      '  return _G[name]',
      'end',
      '',
      'function duplicatedGlobal() return 1 end',
      'function duplicatedGlobal() return _G.dynamic end',
      '',
      'function unknownDependency()',
      '  return missingGlobal()',
      'end',
      '',
      'function collidingExport() return 3 end',
      'collidingExport = { value = 4 }',
    ]));

    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'duplicatedGlobal', targetModule: RISULUA_MODULE_TABLE_DUPLICATE_GLOBALS_PATH }),
    ]));
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'dynamicPublic', reason: 'preserve:dynamic-global-reference-risk' }),
      expect.objectContaining({ originalName: 'duplicatedGlobal', reason: 'preserve:dynamic-global-reference-risk' }),
      expect.objectContaining({ originalName: 'unknownDependency', reason: 'preserve:ambiguous' }),
      expect.objectContaining({ originalName: 'collidingExport', reason: 'preserve:host-visible-global-unsafe-bridge' }),
    ]));
  });

  it('does not generate unsafe public globals as domain dependencies', async () => {
    const result = await classify(lines([
      'function duplicatedDomain() return 1 end',
      'function duplicatedDomain() return missingGlobal() end',
      '',
      'local function usesDuplicatedDomain()',
      '  return duplicatedDomain()',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.symbols).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'usesDuplicatedDomain', classification: 'extract:domain-function' }),
    ]));
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'usesDuplicatedDomain',
        reason: 'preserve:captures-mutable-state',
      }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'usesDuplicatedDomain',
        generationStatus: 'blocked',
        generationBlockedReasons: expect.arrayContaining([
          'Captures bindings that cannot be rewritten as module dependencies: duplicatedDomain.',
        ]),
      }),
    ]));
  });

  it('extracts private top-level locals only when lexical facts are safe', async () => {
    const result = await classify(lines([
      'local function normalizeName(value)',
      '  return string.lower(value)',
      'end',
      '',
      'local function scoreDeck(cards)',
      '  return #cards * 10',
      'end',
      '',
      'local outside = 0',
      'local function bumpOutside()',
      '  outside = outside + 1',
      'end',
    ]));

    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'normalizeName',
        classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
      }),
      expect.objectContaining({
        originalName: 'scoreDeck',
        classification: 'extract:pure-helper',
        targetModule: RISULUA_MODULE_TABLE_COMMON_HELPERS_PATH,
      }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'scoreDeck',
        autoGenerated: false,
        generationStatus: 'report-only',
        recommendedPath: 'lua/domain/score_deck.risulua',
      }),
      expect.objectContaining({
        name: 'bumpOutside',
        autoGenerated: false,
        generationStatus: 'report-only',
        recommendedPath: 'lua/domain/bump_outside.risulua',
      }),
    ]));
    expect(result.refactorMap.modules.map((moduleContract) => moduleContract.path)).not.toContain('lua/domain/score_deck.risulua');
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'bumpOutside', reason: 'preserve:captures-mutable-state' }),
    ]));
  });

  it('classifies nested helpers as pure host-read parameterized or preserved unsafe', async () => {
    const result = await classify(lines([
      'local changedVars = { count = 0 }',
      'function onOutput(text)',
      '  local suffix = "!"',
      '  local function decorate(value)',
      '    return string.lower(value)',
      '  end',
      '  local function readMood(key)',
      '    return getChatVar(key)',
      '  end',
      '  local function appendSuffix(value)',
      '    return value .. suffix',
      '  end',
      '  local function mutateTable()',
      '    changedVars.count = changedVars.count + 1',
      '  end',
      '  local function writeHost()',
      '    setChatVar("last", text)',
      '  end',
      '  return decorate(text) .. readMood("mood") .. appendSuffix(text)',
      'end',
    ]));

    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'decorate', classification: 'extract:pure-helper', targetModule: 'lua/handler_helpers/output_helpers.risulua' }),
      expect.objectContaining({ originalName: 'readMood', classification: 'extract:host-read-helper', targetModule: 'lua/handler_helpers/output_helpers.risulua' }),
      expect.objectContaining({ originalName: 'appendSuffix', classification: 'extract:parameterized-read-helper', targetModule: 'lua/handler_helpers/output_helpers.risulua' }),
    ]));
    expect(result.parameterizedHelpers).toEqual([
      expect.objectContaining({ originalName: 'appendSuffix', capturedReads: ['suffix'], reason: 'handler-local-read-parameterized' }),
    ]);
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'mutateTable', reason: 'preserve:captured-table-mutation' }),
      expect.objectContaining({ originalName: 'writeHost', reason: 'preserve:host-write-order' }),
    ]));
  });

  it('promotes safe private domain helpers when validated domain generation is requested', async () => {
    const result = await classify(lines([
      'local function scoreDeck(cards)',
      '  return #cards * 10',
      'end',
      '',
      'local function writeQuestState(value)',
      '  setChatVar("quest", value)',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'scoreDeck',
        classification: 'extract:domain-function',
        targetModule: 'lua/domain/score_deck.risulua',
        globalBridge: false,
      }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'scoreDeck',
        generationStatus: 'generated',
        generatedPath: 'lua/domain/score_deck.risulua',
        autoGenerated: true,
      }),
      expect.objectContaining({
        name: 'writeQuestState',
        generationStatus: 'generated',
        generatedPath: 'lua/domain/write_quest_state.risulua',
        autoGenerated: true,
      }),
    ]));
  });

  it('extracts public domain functions without main global bridge assignments', async () => {
    const result = await classify(lines([
      'function buildTargetStatus(triggerId)',
      '  return getChatVar(triggerId, "ct_Target_Name") or ""',
      'end',
      '',
      'function onOutput(triggerId)',
      '  return buildTargetStatus(triggerId)',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    const domainSymbol = result.refactorMap.symbols.find((symbol) => symbol.originalName === 'buildTargetStatus');
    expect(domainSymbol).toEqual(expect.objectContaining({
      originalName: 'buildTargetStatus',
      classification: 'extract:domain-function',
      targetModule: 'lua/domain/build_target_status.risulua',
      globalBridge: false,
    }));
    expect(domainSymbol?.bridge).toBeUndefined();
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'buildTargetStatus',
        generationStatus: 'generated',
        generatedPath: 'lua/domain/build_target_status.risulua',
        autoGenerated: true,
      }),
    ]));
  });

  it('promotes private domain helpers that capture generated variable-store constants', async () => {
    const result = await classify(lines([
      'local CORRUPTION_MAX_LEVEL = 5',
      '',
      'local function getCorruptionTotalExpForLevel(level)',
      '  level = math.max(0, math.floor(tonumber(level) or 0))',
      '  level = math.min(level, CORRUPTION_MAX_LEVEL)',
      '  return level * 100',
      'end',
    ]), {
      domainGeneration: 'validated',
      variableStoreNames: ['CORRUPTION_MAX_LEVEL'],
    });

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'getCorruptionTotalExpForLevel',
        classification: 'extract:domain-function',
        targetModule: 'lua/domain/get_corruption_total_exp_for_level.risulua',
      }),
    ]));
    expect(result.refactorMap.preserved).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'getCorruptionTotalExpForLevel' }),
    ]));
  });

  it('blocks private domain helpers with captures that cannot be rewritten as module dependencies', async () => {
    const result = await classify(lines([
      'local LIMIT = 5',
      '',
      'local function scoreWithLimit(value)',
      '  return value + LIMIT',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(result.refactorMap.symbols).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'scoreWithLimit', classification: 'extract:domain-function' }),
    ]));
    expect(result.refactorMap.domainCandidates).toEqual(expect.arrayContaining([
      expect.objectContaining({
        name: 'scoreWithLimit',
        generationStatus: 'blocked',
        generationBlockedReasons: expect.arrayContaining([
          'Captures bindings that cannot be rewritten as module dependencies: LIMIT.',
        ]),
      }),
    ]));
  });

  it('preserves helpers that capture ordinary local scalar state not exported through variable_store', async () => {
    const result = await classify(lines([
      'local counter = 0',
      '',
      'local function nextCounter()',
      '  counter = counter + 1',
      '  return counter',
      'end',
    ]), { domainGeneration: 'validated', variableStoreNames: [] });

    expect(result.refactorMap.symbols).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'nextCounter', classification: 'extract:domain-function' }),
    ]));
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'nextCounter',
        reason: 'preserve:captures-mutable-state',
      }),
    ]));
  });

  it('does not promote variable-store captures through report-mode common helper extraction', async () => {
    const result = await classify(lines([
      'local configValues = { prefix = "Lucky" }',
      '',
      'local function formatLabel(count)',
      '  return configValues.prefix .. count',
      'end',
    ]), { variableStoreNames: ['configValues'] });

    expect(result.refactorMap.symbols).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'formatLabel', classification: 'extract:pure-helper' }),
    ]));
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'formatLabel',
        reason: 'preserve:captures-mutable-state',
      }),
    ]));
  });

  it('extracts risu-trigger functions into button_actions before common or host globals', async () => {
    const result = await classify(lines([
      'local html = [[<button type="button" risu-trigger="toggleSidePanel">Open</button>]]',
      '',
      'local function toggleSidePanel()',
      '  return "ok"',
      'end',
      '',
      'function setAutoSuccess()',
      '  return "auto"',
      'end',
    ]), {
      buttonActionSources: [
        '@@@ OUT\n{{button::Auto::setAutoSuccess}}\n',
      ],
    });

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'toggleSidePanel',
        classification: 'extract:button-action',
        targetModule: RISULUA_MODULE_TABLE_BUTTON_ACTIONS_PATH,
        globalBridge: true,
        bridge: expect.objectContaining({
          mainAssignment: { shape: 'direct_assignment', text: 'toggleSidePanel = __button_actions.toggleSidePanel' },
        }),
      }),
      expect.objectContaining({
        originalName: 'setAutoSuccess',
        classification: 'extract:button-action',
        targetModule: RISULUA_MODULE_TABLE_BUTTON_ACTIONS_PATH,
        globalBridge: true,
        bridge: expect.objectContaining({
          mainAssignment: { shape: 'direct_assignment', text: 'setAutoSuccess = __button_actions.setAutoSuccess' },
        }),
      }),
    ]));
    expect(result.refactorMap.modules).toEqual(expect.arrayContaining([
      expect.objectContaining({
        path: RISULUA_MODULE_TABLE_BUTTON_ACTIONS_PATH,
        requireId: 'button_actions.actions',
        alias: '__button_actions',
        category: 'button-action',
        exports: ['setAutoSuccess', 'toggleSidePanel'],
      }),
    ]));
  });

  it('extracts button actions that capture rewriteable host globals', async () => {
    const result = await classify(lines([
      'local html = [[<button type="button" risu-trigger="generateStartInput">Start</button>]]',
      '',
      'function resetTargetState(triggerId)',
      '  setChatVar(triggerId, "ct_Target_Name", "")',
      'end',
      '',
      'function generateStartInput(triggerId)',
      '  resetTargetState(triggerId)',
      'end',
    ]), { domainGeneration: 'validated' });

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'resetTargetState',
        classification: 'extract:host-global-function',
        targetModule: RISULUA_MODULE_TABLE_GLOBAL_FUNCTIONS_PATH,
        globalBridge: false,
      }),
      expect.objectContaining({
        originalName: 'generateStartInput',
        classification: 'extract:button-action',
        targetModule: RISULUA_MODULE_TABLE_BUTTON_ACTIONS_PATH,
        globalBridge: true,
        bridge: expect.objectContaining({
          mainAssignment: {
            shape: 'direct_assignment',
            text: 'generateStartInput = __button_actions.generateStartInput',
          },
        }),
      }),
    ]));
    expect(result.refactorMap.preserved).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'generateStartInput' }),
    ]));
  });

  it('extracts button actions that capture generated variable-store exports', async () => {
    const result = await classify(lines([
      'local skills = { "Melee", "Magic" }',
      'local skillPointBonusTable = { { points = 0, bonus = 0 } }',
      'local html = [[<button type="button" risu-trigger="Cheat_Set_Skill_Value">Set</button>]]',
      '',
      'Cheat_Set_Skill_Value = async(function(triggerId)',
      '  local selectedIndex = tonumber(alertSelect(triggerId, skills):await()) + 1',
      '  local skillName = skills[selectedIndex]',
      '  local newBonus = skillPointBonusTable[1].bonus',
      '  setChatVar(triggerId, skillName .. "_bonus", newBonus)',
      'end)',
    ]), {
      domainGeneration: 'validated',
      variableStoreNames: ['skills', 'skillPointBonusTable'],
    });

    expect(validateRisuLuaModuleTableRefactorMap(result.refactorMap)).toEqual([]);
    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'Cheat_Set_Skill_Value',
        classification: 'extract:button-action',
        targetModule: RISULUA_MODULE_TABLE_BUTTON_ACTIONS_PATH,
      }),
    ]));
    expect(result.refactorMap.preserved).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'Cheat_Set_Skill_Value' }),
    ]));
  });

  it('preserves button actions that capture unsafe public globals', async () => {
    const result = await classify(lines([
      'local html = [[<button type="button" risu-trigger="doIt">Do</button>]]',
      '',
      'function dynamicPublic(name)',
      '  return _G[name]',
      'end',
      '',
      'function doIt(name)',
      '  return dynamicPublic(name)',
      'end',
    ]));

    expect(result.refactorMap.symbols).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'doIt', classification: 'extract:button-action' }),
    ]));
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'dynamicPublic',
        reason: 'preserve:dynamic-global-reference-risk',
      }),
      expect.objectContaining({
        originalName: 'doIt',
        reason: 'preserve:captures-mutable-state',
        evidence: expect.arrayContaining(['Button action captures external bindings: dynamicPublic.']),
      }),
    ]));
  });

  it('preserves button action candidates that capture mutable local state', async () => {
    const result = await classify(lines([
      'local counter = 0',
      'local html = [[<button type="button" risu-trigger="incrementCounter">+</button>]]',
      '',
      'local function incrementCounter()',
      '  counter = counter + 1',
      '  return counter',
      'end',
    ]));

    expect(result.refactorMap.symbols).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'incrementCounter', classification: 'extract:button-action' }),
    ]));
    expect(result.refactorMap.preserved).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'incrementCounter',
        reason: 'preserve:captures-mutable-state',
        evidence: expect.arrayContaining(['Button action captures external bindings: counter.']),
      }),
    ]));
  });

  it('extracts model host globals that use axLLM and response fields without main bridges', async () => {
    const result = await classify(lines([
      'function callLLMWithRetry(triggerId, prompt)',
      '  local response = axLLM(triggerId, prompt)',
      '  if response and response.success then',
      '    return response.result',
      '  end',
      '  return { success = false, result = "failed" }',
      'end',
    ]));

    expect(result.refactorMap.symbols).toEqual(expect.arrayContaining([
      expect.objectContaining({
        originalName: 'callLLMWithRetry',
        classification: 'extract:host-global-function',
        targetModule: RISULUA_MODULE_TABLE_ASYNC_ACTIONS_PATH,
        globalBridge: false,
      }),
    ]));
    expect(result.refactorMap.preserved).not.toEqual(expect.arrayContaining([
      expect.objectContaining({ originalName: 'callLLMWithRetry', reason: 'preserve:ambiguous' }),
    ]));
  });
});

async function classify(source: string, options?: { domainGeneration?: RisuLuaModuleTableDomainGenerationOption; buttonActionSources?: string[]; variableStoreNames?: string[] }): Promise<RisuLuaModuleTableClassificationResult> {
  const parseResult = await parseRisuLuaModuleTableSource(source);
  const analyzerResult = analyzeRisuLuaModuleTable({ source, parseResult });
  expect(analyzerResult.ok).toBe(true);
  return classifyRisuLuaModuleTableDecisions({ source, sourceFile: 'legacy/original.risulua', analyzerResult, domainGeneration: options?.domainGeneration, buttonActionSources: options?.buttonActionSources, variableStoreNames: options?.variableStoreNames });
}

function lines(sourceLines: string[]): string {
  return `${sourceLines.join('\n')}\n`;
}
