/**
 * Generator for `wiki/_schema/frontmatter.md` — per-class frontmatter field
 * reference. Referenced from SCHEMA.md whenever the LLM writes a narrative
 * page or validates a generated page.
 */

export function generateFrontmatterMd(): string {
  return [
    '---',
    'source: generated',
    'page-class: manual',
    '---',
    '',
    '# Frontmatter schemas',
    '',
    'Per-class field reference. All `_generated/` pages are produced from these schemas.',
    'Narrative pages under `notes/` should follow the `narrative` schema.',
    '',
    '## Common fields (all generated pages)',
    '',
    '| Field | Type | Required | Notes |',
    '|---|---|---|---|',
    '| `source` | string | yes | `generated` or `hand` |',
    '| `page-class` | string | yes | see `_schema/page-classes.md` |',
    '| `artifact` | string | yes (except workspace-level) | Artifact key, e.g. `char_foo` |',
    '| `artifact-type` | string | yes (except workspace-level) | `character`, `module`, or `preset` |',
    '| `generated-at` | ISO-8601 | yes (per-artifact pages) | Omitted on SCHEMA.md, `_schema/**`, `_index.md` |',
    '| `generator` | string | yes | `risu-workbench/analyze/wiki@<version>` |',
    '',
    '## Entity pages (lorebook)',
    '',
    '| Field | Type | Notes |',
    '|---|---|---|',
    '| `entry-type` | string | `lorebook` |',
    '| `entry-slug` | string | Filesystem slug from the source `.risulorebook` file name |',
    '| `folder` | string | Folder path inside the lorebook tree, or empty |',
    '| `activation-mode` | string | `constant`, `keyword`, `keywordMulti`, or `referenceOnly` |',
    '| `keywords` | string[] | Primary trigger keywords |',
    '| `secondary-keywords` | string[] | Secondary keywords (for keywordMulti mode) |',
    '| `reads-vars` | string[] | CBS variables read by this entry |',
    '| `writes-vars` | string[] | CBS variables written by this entry |',
    '',
    '## Chain pages',
    '',
    '| Field | Type | Notes |',
    '|---|---|---|',
    '| `chain-type` | string | `lorebook-activation`, `lua-lorebook-access`, `variable-flow`, `lua-callgraph`, `text-mentions`, `prompt-flow` |',
    '| `entry-point` | string | Starting node of the chain |',
    '| `hops` | number | Number of distinct nodes walked |',
    '| `max-depth` | number | Longest path from entry point |',
    '| `has-cycles` | boolean | True if BFS detected back-edges |',
    '| `cycle-count` | number | Number of back-edges detected |',
    '| `touches-lua` | boolean | True if any Lua node is in this chain |',
    '| `touches-variables` | string[] | Variables referenced anywhere in this chain |',
    '',
    '## Narrative pages (`notes/`)',
    '',
    '| Field | Type | Notes |',
    '|---|---|---|',
    '| `source` | string | `hand` |',
    '| `page-class` | string | `narrative` |',
    '| `companions` | string[] | Relative paths to the `_generated/` pages this note accompanies |',
    '| `tags` | string[] | Free-form tags for the human reader |',
    '',
  ].join('\n');
}
