/**
 * Generator for `wiki/_schema/page-classes.md` — full reference table
 * of the wiki page class hierarchy, referenced from SCHEMA.md.
 */

export function generatePageClassesMd(): string {
  return [
    '---',
    'source: generated',
    'page-class: manual',
    '---',
    '',
    '# Page classes',
    '',
    'This file is the full reference for the `page-class:` frontmatter field.',
    'Read it when you need to confirm what a page is or what order to read pages in.',
    '',
    '## Hierarchy',
    '',
    '```',
    'manual → overview → index → chain → entity → narrative',
    '         └── consolidated ──┘',
    '```',
    '',
    'Read left-to-right. Lower classes (manual, overview) are cheap and always read first.',
    'Higher classes (entity, narrative) are read only after an index narrows the scope.',
    '',
    '## Table',
    '',
    '| Class | Example path | Typical size | Read when |',
    '|---|---|---|---|',
    '| `manual` | `SCHEMA.md`, `_schema/*.md` | ~100 lines | Session start |',
    '| `overview` | `artifacts/<name>/_generated/overview.md` | <1 KB | Before any artifact work |',
    '| `index` | `_index.md`, `lorebook/_index.md`, `chains/_index.md` | 1-3 KB | After overview, to pick a target |',
    '| `consolidated` | `variables.md`, `lua.md`, `regex.md` | 2-10 KB | When all entries of one kind are needed |',
    '| `chain` | `chains/lorebook-activation/<entry>.md` | 1-3 KB | "How does X work?" questions |',
    '| `entity` | `lorebook/<slug>.md` | 1-2 KB | "Edit entity X" tasks |',
    '| `narrative` | `notes/**/*.md` | variable | When design intent or interpretation is required |',
    '',
    '## Traversal cost intuition',
    '',
    '- **manual, overview**: free. Always read at the start of a session or task.',
    '- **index**: cheap. One read narrows the next decision.',
    '- **consolidated**: moderate. Read fully only when you need to scan all entries.',
    '- **chain**: moderate. One chain file per runtime question.',
    '- **entity**: moderate. Target 1-3 entity reads per edit task.',
    '- **narrative**: variable. Read only when the generated data is insufficient.',
    '',
    '## See also',
    '',
    '- `SCHEMA.md` — rules and recipes',
    '- `_schema/frontmatter.md` — required fields per class',
    '',
  ].join('\n');
}
