/**
 * Generator for `wiki/SCHEMA.md` — the skill-style operation manual that
 * LLM agents read at the start of any session touching the wiki.
 *
 * CONTRACT: The output is a deterministic pure function of GENERATOR_VERSION.
 * No timestamps, no environment-dependent fields. Changing any content here
 * requires a version bump so the hash-compare writer picks up the change.
 */

export const GENERATOR_VERSION = '0.1.0';

export function generateSchemaMd(): string {
  return [
    '---',
    'source: generated',
    'page-class: manual',
    `generator: risu-workbench/analyze/wiki@${GENERATOR_VERSION}`,
    '---',
    '',
    '# Wiki Schema',
    '',
    '> **Do not edit.** Regenerated on every `analyze`. User policy lives in `notes/POLICY.md`.',
    '',
    '## When to read this file',
    '',
    'Read this file first in any session that reads or writes files under `wiki/`.',
    'This file defines file ownership, page classes, traversal rules, and recipes.',
    '',
    '## Reading order',
    '',
    '1. `SCHEMA.md` (this file, ~100 lines).',
    '2. `_index.md` — artifact registry for this workspace.',
    '3. `artifacts/<target>/_generated/overview.md` — target artifact manifest.',
    '4. Target sub-file resolved from `overview.md` Contents section.',
    '',
    'Target read budget per task: 3-5 files.',
    '',
    '## File layout contract',
    '',
    '| Path | Owner | Editable by LLM |',
    '|---|---|---|',
    '| `_generated/` (any depth) | analyzer | ❌ wiped on regen |',
    '| `SCHEMA.md`, `_index.md`, `_log.md`, `_schema/` | analyzer | ❌ wiped on regen |',
    '| `notes/` (any depth) | LLM + human | ✅ direct edit |',
    '| `notes/POLICY.md` | human | ✅ edit with user approval; overrides rules in this file |',
    '| `domain/` | human, stable reference | ❌ edit only on explicit user request |',
    '| `workspace.yaml` | human config | ✅ declarative fields only (see recipe: manage-companions) |',
    '',
    'Analyzer never reads `notes/`. Edits to `notes/` do not affect analyzer output.',
    '',
    '## Artifact type discrimination',
    '',
    'Artifact type (character / module / preset) is resolved from',
    '`wiki/workspace.yaml` in v1, and from per-folder manifest files in v2+.',
    'Folder name patterns like `character_*` are NEVER used for type detection.',
    '',
    '## Page classes',
    '',
    'Order: `manual → overview → index → chain → entity → narrative`.',
    'Always read left-to-right. Check frontmatter `page-class:` to confirm position.',
    'Full table: `_schema/page-classes.md`.',
    '',
    '## Traversal rules (cycle-safe)',
    '',
    '1. **"How does X work?"** → `chains/_index.md` → exactly 1 chain file. Chains contain pre-resolved cycles. Do not reconstruct chains by walking entity Relations.',
    '2. **"Edit entity X"** → `overview.md` → entity page → at most 2 neighbors from Relations. Stop reading after the second neighbor.',
    '3. **"Explain this artifact"** → `overview.md` is the only required read. Do not read additional files for high-level answers.',
    '4. **Cross-artifact (DLC)** → Link depth: 1 hop. Chain BFS terminates at artifact boundaries.',
    '5. **Repeated reads** → File read budget per turn: each file at most 1 time.',
    '',
    'Entity Relations sections list one-hop neighbors. They are not used as a starting point for multi-hop traversal.',
    '',
    '## Hard rules',
    '',
    '**NEVER:**',
    '- ❌ Edit anything under `_generated/` or `_schema/`.',
    '- ❌ Edit `SCHEMA.md`, `_index.md`, `_log.md` directly.',
    '- ❌ Walk >2 hops in entity Relations.',
    '- ❌ Use wikilinks `[[...]]`. Use relative markdown links.',
    '- ❌ Cross artifact boundaries in chain walks.',
    '- ❌ Emit content summaries, literal excerpts, or content proportions in `_generated/`. Analyzer outputs only structural facts: counts, edges, metadata, named links.',
    '',
    '**ALWAYS:**',
    '- ✅ Check `source:` frontmatter before editing any page.',
    '- ✅ Read `overview.md` before editing or analyzing an artifact.',
    '- ✅ New narrative → `notes/`, never `_generated/`.',
    '- ✅ If `notes/POLICY.md` exists and conflicts with this file, POLICY wins.',
    '',
    '## Frontmatter schemas',
    '',
    'Every page has `source: generated | hand` and `page-class: <class>`.',
    'Full schemas per class: `_schema/frontmatter.md`.',
    '',
    '## Recipes (read only the one you need)',
    '',
    '- `_schema/recipes/edit-entity.md` — modify a lorebook entry or NPC',
    '- `_schema/recipes/how-does-x-work.md` — trace runtime behavior via chains',
    '- `_schema/recipes/add-new-entry.md` — create entry + link properly',
    '- `_schema/recipes/explain-artifact.md` — "tell me about this character"',
    '- `_schema/recipes/review-unknown-artifact.md` — first-time exploration',
    '- `_schema/recipes/write-narrative.md` — add design intent to notes/',
    '- `_schema/recipes/manage-companions.md` — declare/remove companions in workspace.yaml',
    '',
    'Each recipe is <50 lines.',
    '',
    '## Glossary',
    '',
    'RisuAI domain terms → `domain/` (CBS, lorebook, activation chain, Lua API).',
    'This file does NOT redefine terms.',
    '',
  ].join('\n');
}
