export const RECIPE = [
  '---',
  'source: generated',
  'page-class: manual',
  '---',
  '',
  '# Recipe: explain artifact',
  '',
  'Trigger: user asks "tell me about this character", "what does this module do", or similar high-level questions.',
  '',
  '## Goal',
  'Give a concise answer from `overview.md` alone. Do not fan out.',
  '',
  '## Allowed edits',
  '- ✅ None. This recipe is read-only.',
  '',
  '## Forbidden edits',
  '- ❌ No file modifications.',
  '',
  '## Steps',
  '1. Read `overview.md`.',
  '2. Report the Quick stats, artifact type, and any labels from the DLC / Companions section.',
  '3. If the user asks about a specific aspect (e.g., "how many NPCs"), answer from the stats without reading sub-files.',
  '4. If the user asks for narrative context, check `notes/design-intent.md` and summarize only what is written there.',
  '',
  '## Hard rules',
  '- ❌ Do NOT read entity files or chain files for high-level answers.',
  '- ❌ Do NOT invent descriptive sentences ("this is a Korean fantasy RPG"). Analyzer never emits such content; neither should you.',
  '- ✅ If the user wants depth, ask which aspect and then follow the appropriate recipe.',
  '',
].join('\n');
