export const RECIPE = [
  '---',
  'source: generated',
  'page-class: manual',
  '---',
  '',
  '# Recipe: how does X work',
  '',
  'Trigger: user asks how a runtime behavior works — status display, NPC affinity, event triggers, any "why does X happen".',
  '',
  '## Goal',
  'Locate the relevant pre-resolved chain file and report its narrative to the user.',
  '',
  '## Allowed edits',
  '- ✅ None. This recipe is read-only.',
  '',
  '## Forbidden edits',
  '- ❌ No file modifications. This is an investigation recipe.',
  '',
  '## Steps',
  '1. Read `overview.md` to confirm the artifact has the subject.',
  '2. Read `chains/_index.md` and identify the chain category matching the question:',
  '   - Runtime text display → `lorebook-activation`',
  '   - Variable reset/update → `variable-flow`',
  '   - Lua behavior → `lua-callgraph`',
  '   - Lua-driven lorebook access → `lua-lorebook-access`',
  '3. Read exactly 1 chain file from the identified category.',
  '4. Report the walk steps to the user, citing the chain file by path.',
  '',
  '## Hard rules',
  '- ❌ Do NOT reconstruct the chain by walking entity Relations. Chains are pre-resolved.',
  '- ❌ Do NOT read more than 1 chain file unless the user asks about multiple behaviors.',
  '- ✅ If the relevant chain file does not exist, say so and suggest the user re-run `--wiki`.',
  '',
].join('\n');
