export const RECIPE = [
  '---',
  'source: generated',
  'page-class: manual',
  '---',
  '',
  '# Recipe: manage companions',
  '',
  'Trigger: user asks to declare, remove, or relabel a DLC/companion relationship between artifacts.',
  '',
  '## Goal',
  'Add, remove, or update entries in `wiki/workspace.yaml` and instruct the user to re-run analyze.',
  '',
  '## Allowed edits',
  '- ✅ `wiki/workspace.yaml` (user-owned config)',
  '',
  '## Forbidden edits',
  '- ❌ Anything under `_generated/`, `_schema/`, or `SCHEMA.md`',
  '- ❌ Rewriting `labels:` values by paraphrasing. Confirm exact text with the user first.',
  '',
  '## Steps',
  '1. Read `wiki/workspace.yaml`. If missing, create it with the minimal template below.',
  '2. For a new companion declaration:',
  '   - Find or create the main artifact key under `companions:`',
  '   - Append the companion artifact key to its list',
  '   - Do NOT add a reverse `extends:` field — analyzer derives it',
  '3. For removal: delete the line from the companions list.',
  '4. For relabeling: edit the `labels:` map. Text is rendered literally — no paraphrasing.',
  '5. Preserve existing YAML comments and key order where possible.',
  '6. Tell the user to re-run `risu-core analyze <artifact> --wiki` to regenerate overview.md with the new companion links.',
  '',
  '## Template',
  '',
  '```yaml',
  'artifacts:',
  '  - path: ./character_foo',
  '    type: character',
  '',
  'companions:',
  '  char_foo:',
  '    - module_foo_dlc',
  '',
  'labels:',
  '  char_foo: "Main character card"',
  '  module_foo_dlc: "Expansion DLC"',
  '```',
  '',
  '## Hard rules',
  '- ❌ Do NOT run analyzer commands yourself — only advise the user.',
  '- ❌ Do NOT modify `labels:` values by paraphrasing. Ask for the exact text.',
  '- ❌ Do NOT add fields other than `artifacts`, `companions`, `labels`. Unknown fields are silently ignored.',
  '',
].join('\n');
