export const RECIPE = [
  '---',
  'source: generated',
  'page-class: manual',
  '---',
  '',
  '# Recipe: review unknown artifact',
  '',
  'Trigger: first time you are working with an artifact in this session. You need a mental map before any edits.',
  '',
  '## Goal',
  'Build enough context for follow-up tasks in at most 5 reads.',
  '',
  '## Allowed edits',
  '- ✅ None during review. Edits belong to specific follow-up recipes.',
  '',
  '## Forbidden edits',
  '- ❌ No file modifications during review.',
  '',
  '## Steps',
  '1. Read `SCHEMA.md` (skip if already in context).',
  '2. Read `overview.md` for the artifact.',
  '3. Read `lorebook/_index.md` if the artifact has lorebook entries.',
  '4. Read `chains/_index.md` to see which runtime flows exist.',
  '5. Stop. Further reads depend on the specific task the user will ask next.',
  '',
  '## Hard rules',
  '- ❌ Do NOT pre-read entity files "just in case". Entity reads are driven by task, not exploration.',
  '- ❌ Do NOT read `variables.md` / `lua.md` / `regex.md` unless the overview stats show they are the dominant component.',
  '- ✅ After this recipe, announce what you learned and ask the user what task they want to perform.',
  '',
].join('\n');
