export const RECIPE = [
  '---',
  'source: generated',
  'page-class: manual',
  '---',
  '',
  '# Recipe: write narrative',
  '',
  'Trigger: user asks you to add design intent, interpretation, or commentary to an entity, chain, or the artifact as a whole.',
  '',
  '## Goal',
  'Create or update a markdown file under `notes/` that accompanies a `_generated/` page.',
  '',
  '## Allowed edits',
  '- ✅ Any file under `wiki/artifacts/<artifact>/notes/`',
  '',
  '## Forbidden edits',
  '- ❌ Anything under `_generated/` or `_schema/`',
  '- ❌ `SCHEMA.md`, `_index.md`, `_log.md`',
  '',
  '## Steps',
  '1. Identify which `_generated/` page the narrative accompanies (entity, chain, overview).',
  '2. Determine the companion path under `notes/` using the same relative structure:',
  '   - `_generated/lorebook/강유라.md` → `notes/lorebook/강유라.md`',
  '   - `_generated/chains/lorebook-activation/상태창.md` → `notes/chains/상태창-flow.md`',
  '   - `_generated/overview.md` → `notes/design-intent.md`',
  '3. Read the companion `_generated/` page for factual grounding.',
  '4. Read any existing content at the target `notes/` path — append or revise as needed.',
  '5. Write the narrative with `source: hand` frontmatter and a `companions:` field listing the `_generated/` path it accompanies.',
  '',
  '## Hard rules',
  '- ❌ Do NOT duplicate facts already in the `_generated/` page. Narrative is interpretation, not restatement.',
  '- ❌ Do NOT modify the `_generated/` page to "fix" facts you disagree with. Report discrepancies to the user instead.',
  '- ✅ Use frontmatter `tags:` to categorize narrative (e.g., `[design-intent, plot-thread, mechanic]`).',
  '',
].join('\n');
