import {
  ensureDir,
  writeBinary,
  writeJson,
  writeText,
  uniquePath,
  readJsonIfExists,
  readTextIfExists,
  dirExists,
  ensureDirAsync,
  writeBinaryAsync,
  writeJsonAsync,
  writeTextAsync,
  readFileAsync,
} from './fs-helpers';
import {
  decodeCharacterJsonFromChunks,
  parsePngTextChunks,
  stripPngTextChunks,
  PNG_SIGNATURE,
  PNG_1X1_TRANSPARENT,
  JPEG_1X1,
  writePngTextChunks,
  encodeTextChunk,
  encodeChunk,
  crc32,
  isPng,
  isJpeg,
} from './png';
import { parseCardFile, parseCharxFile } from './charx-io';
import {
  readImageMeta,
  readImageMetaFromBuffer,
  type ImageFileInfo,
  type ImageFormat,
  type ImageGenerationInfo,
  type ImageGenerationSource,
  type ImageMeta,
} from './image-meta';
import {
  CHARACTER_ASSET_DIRS,
  buildCharacterAssetManifest,
  collectCharacterAssetEntries,
  computeAssetBuildWarnings,
  loadAssetCatalogFromAssetsDir,
  type AssetBuildWarnings,
  type AssetManifestBuildSummary,
  type CharacterAssetManifest,
  type CharacterAssetManifestEntry,
  type CharacterAssetSubdir,
} from './asset-manifest';
import {
  resolveRegexAssets,
  type ResolveRegexAssetsOptions,
  type ResolveRegexAssetsResult,
  type ResolvedRegexAsset,
} from './regex-asset-resolver';
import {
  bootstrapAssetCatalogFromEntries,
  bootstrapAssetCatalogFromManifest,
  collectAssetCatalogBootstrapEntriesFromManifest,
  previewAssetCatalogBootstrapEntries,
  summarizeAssetCatalogBootstrapGroups,
  type AssetCatalogBootstrapAnomalyReason,
  type AssetCatalogBootstrapEntry,
  type AssetCatalogBootstrapGroupOverride,
  type AssetCatalogBootstrapGroupSummary,
  type AssetCatalogBootstrapMode,
  type AssetCatalogBootstrapOptions,
  type AssetCatalogBootstrapPreviewEntry,
  type AssetCatalogBootstrapSplitOptions,
} from './asset-catalog-bootstrap';
import { extractLorebookNameCandidates } from './lorebook-names';
import { executeLorebookPlan } from './lorebook-io';
import {
  listJsonFilesRecursive,
  listJsonFilesFlat,
  resolveOrderedFiles,
  readJson,
  isDir,
} from './json-listing';
import { encodeModuleRisum, encodeRPack, loadRPackEncodeMap } from './rpack';
import {
  discoverCustomExtensionWorkspace,
  listCanonicalFilesByArtifact,
  type DiscoveredCanonicalFile,
  type DiscoveredMarkerFile,
  type DiscoveredStructuredJsonFile,
  type CustomExtensionWorkspaceDiscovery,
} from './custom-extension-file-discovery';
import {
  RISUMODULE_FILENAME,
  RISUMODULE_KIND,
  RISUMODULE_SCHEMA_VERSION,
  RISUMODULE_SCHEMA_URL,
  parseRisumoduleManifest,
  type RisumoduleManifest,
  type RisumoduleSourceFormat,
} from '../cli/shared/risumodule';
import {
  collectRisuLuaModuleGraphDiagnostics,
  extractRisuLuaStaticRequireReferences,
  listRisuLuaSourceModuleIds,
  listRisuLuaSourceModules,
  moduleIdFromRisuLuaSourcePath,
  resolveRisuLuaModulePath,
  validateRisuLuaModuleId,
  type CollectRisuLuaModuleGraphDiagnosticsOptions,
  type RisuLuaGraphDiagnostic,
  type RisuLuaSourceModuleFile,
  type RisuLuaSourceRange,
  type RisuLuaStaticRequireReference,
} from '../cli/shared/lua-bundler/risulua-modular-resolver';
import {
  appendLogEntry,
  rewriteIndexArtifactsSection,
  writeArtifactFiles,
  writeSchemaIfChanged,
} from '../cli/analyze/shared/wiki/write-protect';
import { AssetHashCache, sha256Hex } from './hmr-asset-hash';
import { buildHmrCharacterPayload, buildHmrModulePayload } from './hmr-build';
import type { HmrAssetSource, HmrBuildResult } from './hmr-build';

const parsePngChunks = parsePngTextChunks;

export {
  parsePngTextChunks,
  stripPngTextChunks,
  decodeCharacterJsonFromChunks,
  parseCharxFile,
  parseCardFile,
  readImageMeta,
  readImageMetaFromBuffer,
  type ImageFileInfo,
  type ImageFormat,
  type ImageGenerationInfo,
  type ImageGenerationSource,
  type ImageMeta,
  CHARACTER_ASSET_DIRS,
  buildCharacterAssetManifest,
  bootstrapAssetCatalogFromEntries,
  bootstrapAssetCatalogFromManifest,
  collectAssetCatalogBootstrapEntriesFromManifest,
  previewAssetCatalogBootstrapEntries,
  summarizeAssetCatalogBootstrapGroups,
  collectCharacterAssetEntries,
  computeAssetBuildWarnings,
  loadAssetCatalogFromAssetsDir,
  resolveRegexAssets,
  extractLorebookNameCandidates,
  type AssetBuildWarnings,
  type AssetCatalogBootstrapAnomalyReason,
  type AssetCatalogBootstrapEntry,
  type AssetCatalogBootstrapGroupOverride,
  type AssetCatalogBootstrapGroupSummary,
  type AssetCatalogBootstrapMode,
  type AssetCatalogBootstrapOptions,
  type AssetCatalogBootstrapPreviewEntry,
  type AssetCatalogBootstrapSplitOptions,
  type AssetManifestBuildSummary,
  type CharacterAssetManifest,
  type CharacterAssetManifestEntry,
  type CharacterAssetSubdir,
  type ResolveRegexAssetsOptions,
  type ResolveRegexAssetsResult,
  type ResolvedRegexAsset,
  ensureDir,
  writeJson,
  writeText,
  writeBinary,
  uniquePath,
  readJsonIfExists,
  readTextIfExists,
  dirExists,
  parsePngChunks,
  executeLorebookPlan,
  listJsonFilesRecursive,
  listJsonFilesFlat,
  resolveOrderedFiles,
  readJson,
  isDir,
  PNG_SIGNATURE,
  PNG_1X1_TRANSPARENT,
  JPEG_1X1,
  writePngTextChunks,
  encodeTextChunk,
  encodeChunk,
  crc32,
  isPng,
  isJpeg,
  encodeModuleRisum,
  encodeRPack,
  loadRPackEncodeMap,
  ensureDirAsync,
  writeBinaryAsync,
  writeJsonAsync,
  writeTextAsync,
  readFileAsync,
  discoverCustomExtensionWorkspace,
  listCanonicalFilesByArtifact,
  type DiscoveredCanonicalFile,
  type DiscoveredMarkerFile,
  type DiscoveredStructuredJsonFile,
  type CustomExtensionWorkspaceDiscovery,
  RISUMODULE_FILENAME,
  RISUMODULE_KIND,
  RISUMODULE_SCHEMA_VERSION,
  RISUMODULE_SCHEMA_URL,
  parseRisumoduleManifest,
  type RisumoduleManifest,
  type RisumoduleSourceFormat,
  collectRisuLuaModuleGraphDiagnostics,
  extractRisuLuaStaticRequireReferences,
  listRisuLuaSourceModuleIds,
  listRisuLuaSourceModules,
  moduleIdFromRisuLuaSourcePath,
  resolveRisuLuaModulePath,
  validateRisuLuaModuleId,
  type CollectRisuLuaModuleGraphDiagnosticsOptions,
  type RisuLuaGraphDiagnostic,
  type RisuLuaSourceModuleFile,
  type RisuLuaSourceRange,
  type RisuLuaStaticRequireReference,
  appendLogEntry,
  rewriteIndexArtifactsSection,
  writeArtifactFiles,
  writeSchemaIfChanged,
  AssetHashCache,
  sha256Hex,
  buildHmrCharacterPayload,
  buildHmrModulePayload,
  type HmrAssetSource,
  type HmrBuildResult,
};

export * from './risulua-runtime';
